import Fastify from 'fastify';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {ZodError} from 'zod';
const mocks=vi.hoisted(()=>({query:vi.fn(),convert:vi.fn(),role:'SUPERADMIN'}));
vi.mock('../database/client.js',()=>({pool:{query:mocks.query},withTransaction:async(work:any)=>work({query:mocks.query})}));
vi.mock('../types.js',()=>({allow:(...roles:string[])=>async(request:any)=>{if(!roles.includes(mocks.role))throw Object.assign(new Error('Forbidden'),{statusCode:403});request.user={id:'a1000000-0000-4000-8000-000000000001',role:mocks.role}}}));
vi.mock('../images/convert.js',()=>({convertToWebp:mocks.convert}));
import {landingContentRoutes,newsInput,priceInput} from './landing-content.js';
const id='a2000000-0000-4000-8000-000000000002';
const input={headline:'Informasi Harga Bahan Pokok',destination:'https://drive.google.com/file/d/example/view',active:true};
const apps:ReturnType<typeof Fastify>[]=[];
async function setup(){const app=Fastify();apps.push(app);app.setErrorHandler((error,_request,reply)=>reply.code(error instanceof ZodError?400:(error as any).statusCode||500).send({message:(error as Error).message}));await app.register(landingContentRoutes);return app}
beforeEach(()=>{vi.clearAllMocks();mocks.role='SUPERADMIN';mocks.query.mockResolvedValue({rows:[{id,...input,thumbnail:'https://example.com/photo.webp'}],rowCount:1});mocks.convert.mockResolvedValue(Buffer.from('canonical-webp'))});
afterEach(async()=>{await Promise.all(apps.splice(0).map(app=>app.close()))});
describe('landing content',()=>{
  it.each(['javascript:alert(1)','data:text/html,hello','http://example.com','https://user:pass@example.com'])('rejects unsafe destination %s',destination=>{expect(newsInput.safeParse({...input,destination}).success).toBe(false)});
  it('supports official documents without invented prices or mandatory images',()=>{expect(priceInput.parse(input)).toEqual(input);expect(priceInput.safeParse({...input,price:5000}).success).toBe(false)});
  it.each(['ADMIN','BUYER'])('rejects management access for %s',async role=>{mocks.role=role;const app=await setup();for(const [method,url,payload] of [['GET','/management/content',undefined],['POST','/management/content/news',input],['PUT',`/management/content/prices/${id}`,input],['DELETE',`/management/content/news/${id}`,undefined],['GET',`/management/content/news/${id}/thumbnail`,undefined]] as const){expect((await app.inject({method,url,payload})).statusCode).toBe(403)}expect(mocks.query).not.toHaveBeenCalled()});
  it('exposes only active content publicly with bounded queries',async()=>{mocks.role='BUYER';const app=await setup();expect((await app.inject({url:'/website/content'})).statusCode).toBe(200);expect(mocks.query.mock.calls.every(([sql])=>sql.includes('WHERE active'))).toBe(true);expect(mocks.query.mock.calls.find(([sql])=>sql.includes('FROM landing_news'))![0]).toContain('LIMIT 50');expect(mocks.query.mock.calls.find(([sql])=>sql.includes('FROM landing_prices'))![0]).toContain('LIMIT 3')});
  it('requires a thumbnail for new news',async()=>{const app=await setup();expect((await app.inject({method:'POST',url:'/management/content/news',payload:input})).statusCode).toBe(400);expect(mocks.query).not.toHaveBeenCalled()});
  it('creates official document links and logs the mutation',async()=>{const app=await setup();expect((await app.inject({method:'POST',url:'/management/content/prices',payload:input})).statusCode).toBe(200);expect(mocks.query.mock.calls.some(([sql])=>sql.includes('INSERT INTO landing_prices'))).toBe(true);expect(mocks.query.mock.calls.find(([sql])=>sql.includes('INSERT INTO audit_logs'))![1]).toContain('LANDING_PRICE')});
  it('normalizes uploaded images and never duplicates image bytes in audit',async()=>{const app=await setup();const thumbnail='data:image/webp;base64,YWJj';expect((await app.inject({method:'POST',url:'/management/content/news',payload:{...input,thumbnail}})).statusCode).toBe(200);expect(mocks.convert).toHaveBeenCalled();const audit=mocks.query.mock.calls.find(([sql])=>sql.includes('INSERT INTO audit_logs'))![1][4];expect(audit).not.toContain('base64');expect(audit).toContain('updated')});
  it('allows removing an optional document thumbnail',async()=>{const app=await setup();expect((await app.inject({method:'PUT',url:`/management/content/prices/${id}`,payload:{...input,thumbnail:''}})).statusCode).toBe(200);expect(mocks.query.mock.calls[0][1][1]).toBe('')});
  it('caps entries to avoid unbounded public payloads',async()=>{mocks.query.mockImplementation(async(sql:string)=>({rows:sql.includes('count(*)')?[{count:50}]:[],rowCount:0}));const app=await setup();expect((await app.inject({method:'POST',url:'/management/content/prices',payload:input})).statusCode).toBe(409);expect(mocks.query.mock.calls.some(([sql])=>sql.includes('INSERT INTO landing_prices'))).toBe(false)});
  it('preserves an existing thumbnail when editing just the headline/link',async()=>{const app=await setup();expect((await app.inject({method:'PUT',url:`/management/content/news/${id}`,payload:input})).statusCode).toBe(200);expect(mocks.query.mock.calls[0][1][1]).toBeNull();expect(mocks.query.mock.calls[0][1][4]).toBe(id)});
  it('does not expose thumbnails of unpublished items',async()=>{mocks.query.mockResolvedValue({rows:[],rowCount:0});const app=await setup();expect((await app.inject({url:`/website/news/${id}/thumbnail`})).statusCode).toBe(404);expect(mocks.query.mock.calls[0][0]).toContain('AND active')});
  it('returns 404 for missing updates/deletions',async()=>{mocks.query.mockResolvedValue({rows:[],rowCount:0});const app=await setup();expect((await app.inject({method:'PUT',url:`/management/content/news/${id}`,payload:input})).statusCode).toBe(404);expect((await app.inject({method:'DELETE',url:`/management/content/news/${id}`})).statusCode).toBe(404)});
});
