import {useEffect,useRef,useState,type FormEvent} from 'react';
import {LogOut,X} from 'lucide-react';
import {api,type User} from './api';
import './account-settings.css';

export type ManagedAccount={id:string;name:string;username:string;email:string|null;role:User['role'];active:boolean;organization:string|null;phone:string|null;address:string|null;gmapsUrl:string|null;managerId:string|null};

export function AccountEditor({account,admins,onClose,onSaved}:{account:ManagedAccount;admins?:{id:string;name:string;active:boolean}[];onClose:()=>void;onSaved:()=>Promise<unknown>}){
  const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[password,setPassword]=useState('');const formRef=useRef<HTMLFormElement>(null);
  const closeRef=useRef(onClose);closeRef.current=onClose;
  useEffect(()=>{if(error){const fields=formRef.current?.querySelector('.account-editor-fields');if(fields)fields.scrollTop=0}},[error]);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const old=document.body.style.overflow;document.body.style.overflow='hidden';formRef.current?.querySelector<HTMLInputElement>('input')?.focus();return()=>{document.body.style.overflow=old;previous?.focus()}},[]);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{
    event.preventDefault();if(busy)return;const d=new FormData(event.currentTarget);setError('');
    if(password&&password!==d.get('confirmPassword')){setError('Konfirmasi password baru belum sama.');return;}
    const managerId=d.get('adminId')||null;
    const kitchen=account.role==='BUYER'?{name:d.get('kitchenName'),phone:d.get('phone'),address:d.get('address'),gmapsUrl:d.get('gmapsUrl'),...(admins&&managerId!==account.managerId?{adminId:managerId}:{})}:undefined;
    setBusy(true);try{await api(`/accounts/${account.id}`,{method:'PATCH',body:JSON.stringify({fullName:d.get('fullName'),username:d.get('username'),email:d.get('email'),active:d.get('active')==='true',kitchen,...(password?{password,currentPassword:d.get('currentPassword')}:{})})});await onSaved();onClose()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}
  };
  return <div className="account-editor-backdrop"><section className="account-editor" role="dialog" aria-modal="true" aria-labelledby="edit-account-title" onKeyDown={event=>{if(event.key==='Escape'&&!busy){event.preventDefault();closeRef.current()}if(event.key==='Tab'){const nodes=Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),summary'));const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}}}>
    <header><div><h2 id="edit-account-title">Edit akun</h2><p>{account.name}</p></div><button type="button" aria-label="Tutup edit akun" disabled={busy} onClick={onClose}><X size={18}/></button></header>
    <form ref={formRef} onSubmit={submit}><fieldset disabled={busy} className="account-editor-fields">
      {error&&<p className="account-error" role="alert">{error}</p>}
      <section className="account-section"><h3>Identitas akun</h3><div className="account-fields"><label>Nama lengkap<input name="fullName" required minLength={2} maxLength={120} defaultValue={account.name}/></label><label>Username<input name="username" required minLength={3} maxLength={64} pattern="[a-zA-Z0-9][a-zA-Z0-9._-]*" autoCapitalize="none" defaultValue={account.username}/></label><label>Email (opsional)<input name="email" type="email" maxLength={254} defaultValue={account.email||''}/></label><label>Status akun<select name="active" defaultValue={String(account.active)}><option value="true">Aktif</option><option value="false">Nonaktif</option></select></label></div></section>
      {account.role==='BUYER'&&<section className="account-section"><h3>Informasi dapur</h3><div className="account-fields"><label>Nama dapur<input name="kitchenName" required minLength={2} maxLength={120} defaultValue={account.organization||''}/></label><label>Nomor HP<input name="phone" type="tel" required minLength={6} maxLength={30} defaultValue={account.phone||''}/></label><label className="account-field-full">Alamat<textarea name="address" required minLength={5} maxLength={300} rows={3} defaultValue={account.address||''}/></label><label className="account-field-full">Google Maps (opsional)<input name="gmapsUrl" type="url" defaultValue={account.gmapsUrl||''}/></label>{admins&&<label className="account-field-full">Admin pengelola<select name="adminId" defaultValue={account.managerId||''}><option value="">Belum ditentukan</option>{admins.filter(a=>a.active||a.id===account.managerId).map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label>}</div></section>}
      <details className="account-section account-password"><summary>Reset password</summary><p>Password baru akan mencabut semua sesi lama akun ini.</p><div className="account-fields"><label>Password baru<input name="password" type="password" minLength={8} maxLength={72} autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)}/></label><label>Konfirmasi password baru<input name="confirmPassword" type="password" required={!!password} minLength={8} maxLength={72} autoComplete="new-password"/></label>{password&&<label className="account-field-full">Password Anda saat ini<input name="currentPassword" type="password" required minLength={8} maxLength={72} autoComplete="current-password"/></label>}</div></details>
    </fieldset><footer><button type="button" disabled={busy} onClick={onClose}>Batal</button><button className="primary" disabled={busy}>{busy?'Menyimpan…':'Simpan perubahan'}</button></footer></form>
  </section></div>;
}

export function ManagedBuyerAccounts(){
  const[accounts,setAccounts]=useState<ManagedAccount[]>([]);const[editing,setEditing]=useState<ManagedAccount|null>(null);const[notice,setNotice]=useState('');const[loading,setLoading]=useState(true);
  const load=async()=>{try{setAccounts(await api<ManagedAccount[]>('/accounts'));setNotice('')}catch(reason){setNotice((reason as Error).message)}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  return <section className="panel managed-account-panel"><div className="panel-heading"><h2>Akun dapur</h2></div>{notice&&<p className="account-error" role="alert">{notice}<button onClick={()=>void load()}>Coba lagi</button></p>}{loading?<p>Memuat akun…</p>:accounts.length===0?<p>Belum ada akun dapur yang dikelola.</p>:<div className="managed-account-list">{accounts.map(a=><article key={a.id}><div><strong>{a.organization||a.name}</strong><span>{a.username} · {a.active?'Aktif':'Nonaktif'}</span><small>{a.phone||'Nomor HP belum diisi'}</small></div><button onClick={()=>setEditing(a)}>Edit akun</button></article>)}</div>}{editing&&<AccountEditor account={editing} onClose={()=>setEditing(null)} onSaved={load}/>}</section>;
}

export function BuyerSettings({user,onLogout}:{user:User;onLogout:()=>void}){
  const[profile,setProfile]=useState(user);const[notice,setNotice]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState<'phone'|'password'|null>(null);const[passwordDone,setPasswordDone]=useState(false);
  useEffect(()=>{let alive=true;void api<User>('/auth/me').then(data=>{if(alive)setProfile(data)}).catch(reason=>{if(alive)setError((reason as Error).message)});return()=>{alive=false}},[]);
  const save=async(event:FormEvent<HTMLFormElement>,kind:'phone'|'password')=>{event.preventDefault();if(busy)return;const form=event.currentTarget;const d=new FormData(form);setNotice('');setError('');if(kind==='password'&&d.get('newPassword')!==d.get('confirmation')){setError('Konfirmasi password baru belum sama.');return;}setBusy(kind);try{await api('/auth/me',{method:'PATCH',body:JSON.stringify(kind==='phone'?{phone:d.get('phone')}:{currentPassword:d.get('currentPassword'),newPassword:d.get('newPassword')})});if(kind==='phone'){setProfile(p=>({...p,phone:String(d.get('phone'))}));setNotice('Nomor HP berhasil diperbarui.')}else{form.reset();setPasswordDone(true)}}catch(reason){setError((reason as Error).message)}finally{setBusy(null)}};
  return <div className="buyer-settings"><h1>Profil dapur</h1>{notice&&<p className="account-notice" role="status">{notice}</p>}{error&&<p className="account-error" role="alert">{error}</p>}<div className="buyer-settings-grid"><section className="panel account-section"><h2>{profile.organization||profile.name}</h2><dl><div><dt>Username</dt><dd>{profile.username}</dd></div><div><dt>Nama akun</dt><dd>{profile.name}</dd></div><div><dt>Alamat</dt><dd>{profile.address||'Belum diisi'}</dd></div></dl>{profile.gmapsUrl&&<a className="buyer-settings-location" href={profile.gmapsUrl} target="_blank" rel="noreferrer">Lihat lokasi dapur</a>}<form onSubmit={event=>void save(event,'phone')}><label>Nomor HP dapur<input key={profile.phone} disabled={!!busy||passwordDone} name="phone" type="tel" minLength={6} maxLength={30} required defaultValue={profile.phone||''}/></label><button className="primary" disabled={!!busy||passwordDone}>{busy==='phone'?'Menyimpan…':'Simpan nomor HP'}</button></form><p className="account-hint">Perubahan identitas dan alamat dibantu admin pengelola.</p></section><section className="panel account-section"><h2>Keamanan akun</h2>{passwordDone?<div role="status"><p>Password berhasil diubah. Silakan masuk kembali menggunakan password baru.</p><button className="primary" onClick={onLogout}>Masuk kembali</button></div>:<form onSubmit={event=>void save(event,'password')}><label>Password saat ini<input name="currentPassword" type="password" minLength={8} maxLength={72} required autoComplete="current-password"/></label><label>Password baru<input name="newPassword" type="password" minLength={8} maxLength={72} required autoComplete="new-password"/></label><label>Konfirmasi password baru<input name="confirmation" type="password" minLength={8} maxLength={72} required autoComplete="new-password"/></label><p className="account-hint">Minimal 8 karakter. Semua sesi lama akan berakhir.</p><button className="primary" disabled={!!busy}>{busy==='password'?'Menyimpan…':'Ubah password'}</button></form>}<div className="account-logout"><button className="logout-danger" type="button" disabled={!!busy} onClick={onLogout}><LogOut size={18} aria-hidden="true"/>Keluar dari akun</button></div></section></div></div>;
}
