import {ProductImage} from './ProductImage';
import { validOrderQuantity } from './order-input';
import { useEffect, useState, type FormEvent } from 'react';
import { CheckCircle2, ClipboardCheck, Package, Plus, Search, ShoppingCart, X } from 'lucide-react';
import { api, type User } from './api';
import {BuyerSettings} from './AccountSettings';
import {ProductOrderDialog} from './ProductOrderDialog';

type Catalog = { id: string; sku: string; name: string; category: string; image: string | null; orderUnit: string; priceUnit: string; weighingRequired: boolean; estimatedKgPerUnit: number | null; salePrice: number; availableStock: number };
type OrderItem = { id: string; name: string; quantity: number; orderUnit: string; priceUnit: string; unitPrice: number; actualWeightKg: number | null };
type Order = { id: string; orderNo: string; status: string; neededDate: string; kitchen: string; estimatedTotal: number; finalTotal: number | null; currentTotal: number; createdAt: string; items: OrderItem[] };
type SpecialRequest = { id: string; requestNo: string; name: string; quantity: number; unit: string; note: string | null; status: 'PENDING' | 'APPROVED' | 'REJECTED'; orderId: string | null; createdAt: string; kitchen: string };
const money = (value: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value);
const statusLabel: Record<string, string> = { SUBMITTED: 'Pesanan masuk', PREPARING: 'Sedang disiapkan', SHIPPED: 'Dalam pengiriman', AWAITING_KITCHEN: 'Menunggu konfirmasi dapur', COMPLETED: 'Selesai', CANCELLED: 'Dibatalkan' };

export function BuyerPanel({ page, user, go, onLogout }: { page: string; user: User; go: (page: string) => void; onLogout: () => void }) {
  const [catalog, setCatalog] = useState<Catalog[]>([]); const [orders, setOrders] = useState<Order[]>([]); const [requests, setRequests] = useState<SpecialRequest[]>([]); const [quantities, setQuantities] = useState<Record<string, number>>({}); const [notice, setNotice] = useState(''); const [search, setSearch] = useState(''); const [category, setCategory] = useState('Semua'); const [cartOpen, setCartOpen] = useState(false); const [requestOpen, setRequestOpen] = useState(false); const [selectedProduct, setSelectedProduct] = useState<Catalog | null>(null); const [draftQuantity, setDraftQuantity] = useState('1'); const [history, setHistory] = useState(false);
  const load = () => Promise.all([api<Catalog[]>('/catalog').then(setCatalog), api<Order[]>('/orders').then(setOrders), api<SpecialRequest[]>('/special-requests').then(setRequests)]); useEffect(() => { load() }, []);
  const cartItems = catalog.filter(product => (quantities[product.id] || 0) > 0); const cartCount = cartItems.length; const cartTotal = cartItems.reduce((sum, product) => sum + (quantities[product.id] || 0) * Number(product.salePrice) * (product.weighingRequired ? Number(product.estimatedKgPerUnit) : 1), 0);
  const checkout = async () => { const items = cartItems.map(product => ({ adminProductId: product.id, quantity: quantities[product.id] })); if (!items.length) return setNotice('Keranjang masih kosong.'); try { await api('/orders', { method: 'POST', body: JSON.stringify({ neededDate: new Date(Date.now() + 86400000).toISOString().slice(0, 10), idempotencyKey: crypto.randomUUID(), items }) }); setQuantities({}); setCartOpen(false); setNotice('Pesanan berhasil dikirim ke admin koperasi.'); await load() } catch (reason) { setNotice((reason as Error).message) } };
  const confirm = async (ids: string[]) => { for (const id of ids) await api(`/orders/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status: 'COMPLETED' }) }); setNotice('Penerimaan barang berhasil dikonfirmasi.'); await load() };
  const requestItem = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { await api('/special-requests', { method: 'POST', body: JSON.stringify({ name: data.get('name'), quantity: data.get('quantity'), unit: data.get('unit'), note: data.get('note') }) }); form.reset(); setRequestOpen(false); setNotice('Permintaan barang dikirim untuk persetujuan admin.'); await load() } catch (reason) { setNotice((reason as Error).message) } };
  if (page === 'dashboard') return <BuyerDashboard user={user} catalog={catalog} orders={orders} requests={requests} go={go} confirm={confirm} />;
  if (page === 'orders') return <BuyerOrders orders={orders} history={history} setHistory={setHistory} confirm={confirm} go={go} />;
  if (page === 'request') return <><PageHeading title="Pesan barang" />{notice && <div className="notice" role="status">{notice}</div>}<section className="panel buyer-request-page"><div className="panel-heading"><h2>Barang di luar katalog</h2></div><BuyerRequestForm onSubmit={requestItem} /></section></>;
  if (page === 'profile') return <BuyerSettings user={user} onLogout={onLogout} />;
  const categories = ['Semua', ...Array.from(new Set(catalog.map(product => product.category))).sort((a, b) => a.localeCompare(b, 'id'))];
  const visible = catalog.filter(product => (category === 'Semua' || product.category === category) && `${product.name} ${product.category}`.toLowerCase().includes(search.toLowerCase()));
  const openProduct = (product: Catalog) => { setSelectedProduct(product); setDraftQuantity(String(quantities[product.id] || 1)) };
  const addToCart = () => { if (!selectedProduct || !validOrderQuantity(draftQuantity, selectedProduct.weighingRequired)) return; setQuantities(current => ({ ...current, [selectedProduct.id]: Number(draftQuantity) })); setSelectedProduct(null); setNotice(`${selectedProduct.name} ditambahkan ke keranjang.`) };
  return <>
    <PageHeading title="Kebutuhan dapur" className="catalog-heading"/>
    {notice&&<div className="notice" role="status">{notice}</div>}
    <section className="panel catalog-panel">
      <div className="catalog-toolbar"><label className="catalog-search"><Search size={18}/><input aria-label="Cari produk atau kategori" type="search" placeholder="Cari produk atau kategori" value={search} onChange={event=>setSearch(event.target.value)}/></label><span><b>{visible.length}</b> produk tersedia</span></div>
      <div className="category-filter" aria-label="Filter kategori">{categories.map(item=><button key={item} className={category===item?'active':''} onClick={()=>setCategory(item)}>{item}</button>)}</div>
      {visible.length?<div className="product-grid">{visible.map(product=><BuyerCatalogProduct key={product.id} product={product} onSelect={()=>openProduct(product)}/>)}</div>:<EmptyState title={search||category!=='Semua'?'Produk tidak ditemukan':'Belum ada produk tersedia'} detail={search||category!=='Semua'?'Coba ubah pencarian atau kategori.':'Katalog akan terisi setelah admin koperasi menambahkan stok.'}/>}
    </section>
    <div className="catalog-floating-actions" role="group" aria-label="Aksi katalog">
      <button className="catalog-fab request-fab" aria-label="Pesan barang di luar katalog" title="Pesan barang di luar katalog" onClick={()=>setRequestOpen(true)}><Plus size={20}/></button>
      <button className="cart-fab catalog-fab" aria-label={`Buka keranjang, ${cartCount} produk`} title="Buka keranjang" onClick={()=>setCartOpen(true)}><ShoppingCart size={20}/><span>{cartCount}</span></button>
    </div>
    {selectedProduct&&<ProductOrderDialog product={selectedProduct} quantity={draftQuantity} onQuantityChange={setDraftQuantity} onAdd={addToCart} onClose={()=>setSelectedProduct(null)}/>}
    {cartOpen&&<Modal title="Keranjang" close={()=>setCartOpen(false)}>{cartItems.length?<><div className="cart-lines">{cartItems.map(product=><div key={product.id}><span><strong>{product.name}</strong><small>{quantities[product.id]} {product.orderUnit}</small></span><b>{money((quantities[product.id]||0)*Number(product.salePrice)*(product.weighingRequired?Number(product.estimatedKgPerUnit):1))}</b><button aria-label={`Hapus ${product.name} dari keranjang`} onClick={()=>setQuantities(current=>({...current,[product.id]:0}))}><X size={16}/></button></div>)}</div><div className="cart-total"><span>Total sementara</span><strong>{money(cartTotal)}</strong></div><div className="modal-actions"><button onClick={()=>setCartOpen(false)}>Tutup</button><button className="primary" onClick={checkout}>Proses pesanan</button></div></>:<EmptyState title="Keranjang masih kosong" detail="Pilih produk dari katalog untuk memulai pesanan."/>}</Modal>}
    {requestOpen&&<Modal title="Pesan barang di luar katalog" close={()=>setRequestOpen(false)}><BuyerRequestForm onSubmit={requestItem} onCancel={()=>setRequestOpen(false)}/></Modal>}
  </>;
}

export function BuyerCatalogProduct({product,onSelect}:{product:Catalog;onSelect:()=>void}) {
  return <article className="product-card catalog-product" role="button" tabIndex={0} aria-label={`Pesan ${product.name}`} onClick={onSelect} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect();}}}>
    <div className="product-image"><ProductImage src={product.image||'/assets/logo/logo.webp'} alt={product.name} loading="lazy"/></div>
    <div><small>{product.category}</small><h2>{product.name}</h2><p>{money(Number(product.salePrice))} / {product.priceUnit}</p></div>
  </article>;
}

function BuyerRequestForm({ onSubmit, onCancel }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void; onCancel?: () => void }) { return <form className="request-form" onSubmit={onSubmit}><label>Nama barang *<input name="name" required placeholder="Contoh: Daging ayam fillet" /></label><div className="form-row"><label>Jumlah *<input name="quantity" type="number" min="0.001" step="0.001" required /></label><label>Satuan *<input name="unit" required placeholder="Kilogram" /></label></div><label>Catatan<textarea name="note" rows={3} placeholder="Merek, kualitas, atau kebutuhan khusus" /></label><div className="modal-actions">{onCancel && <button type="button" onClick={onCancel}>Batal</button>}<button className="primary">Kirim permintaan</button></div></form> }

function BuyerDashboard({ user, catalog, orders, requests, go, confirm }: { user: User; catalog: Catalog[]; orders: Order[]; requests: SpecialRequest[]; go: (page: string) => void; confirm: (ids: string[]) => Promise<void> }) { const active = orders.filter(order => !['COMPLETED', 'CANCELLED'].includes(order.status)); const awaiting = orders.filter(order => order.status === 'AWAITING_KITCHEN'); const pending = requests.filter(request => request.status === 'PENDING'); return <div className="buyer-dashboard-home"><PageHeading title={user.organization || user.name} action={<button className="primary" onClick={() => go('catalog')}>Buka katalog</button>} /><section className="buyer-metrics"><Metric label="Pesanan aktif" value={active.length} note="Sedang diproses koperasi" icon={<ClipboardCheck />} /><Metric label="Konfirmasi dapur" value={awaiting.length} note="Perlu konfirmasi penerimaan" icon={<CheckCircle2 />} /><Metric label="Produk tersedia" value={catalog.length} note="Siap dilihat di katalog" icon={<Package />} /></section><div className="dashboard-content-sheet"><div className="buyer-dashboard-grid"><section className="panel activity-panel"><div className="panel-heading"><h2>Aktivitas pesanan</h2><button className="text-action" onClick={() => go('orders')}>Lihat semua</button></div><BuyerOrderGroups orders={active.slice(0, 5)} confirm={confirm} compact emptyTitle="Belum ada pesanan yang sedang diproses" emptyDetail="Pilih kebutuhan dari katalog untuk membuat pesanan." emptyAction={<button className="primary activity-empty-action" onClick={() => go('catalog')}><ShoppingCart size={16} />Mulai pengadaan</button>} /></section></div><section className="panel requests-panel"><div className="panel-heading"><h2>Permintaan barang</h2></div>{pending.length ? pending.map(request => <div className="request-row" key={request.id}><span><strong>{request.name}</strong><small>{request.quantity} {request.unit}</small></span><span>Menunggu persetujuan</span></div>) : <EmptyState title="Tidak ada permintaan menunggu" detail="Permintaan yang disetujui akan berpindah ke aktivitas pesanan." />}</section></div></div> }

function BuyerOrders({ orders, history, setHistory, confirm, go }: { orders: Order[]; history: boolean; setHistory: (value: boolean) => void; confirm: (ids: string[]) => Promise<void>; go: (page: string) => void }) { const visible = orders.filter(order => history ? order.status === 'COMPLETED' : !['COMPLETED', 'CANCELLED'].includes(order.status)); return <><PageHeading title="Pesanan saya" className="orders-heading" /><section className="panel orders-page"><div className="segmented"><button className={!history ? 'active' : ''} onClick={() => setHistory(false)}>Pesanan aktif</button><button className={history ? 'active' : ''} onClick={() => setHistory(true)}>Riwayat selesai</button></div><BuyerOrderGroups orders={visible} confirm={confirm} emptyTitle={history ? 'Belum ada riwayat pesanan' : 'Belum ada pesanan yang sedang diproses'} emptyDetail={history ? 'Pesanan yang telah selesai akan tersimpan di sini.' : 'Pilih kebutuhan dari katalog untuk membuat pesanan.'} emptyAction={!history ? <button className="primary empty-order-action" onClick={() => go('catalog')}><Plus size={16} />Buat pesanan baru</button> : undefined} /></section></> }

export function BuyerOrderGroups({ orders, confirm, compact = false, emptyTitle = 'Tidak ada pesanan aktif', emptyDetail = 'Pesanan baru akan tampil di sini setelah dibuat dari katalog.', emptyAction }: { orders: Order[]; confirm: (ids: string[]) => Promise<void>; compact?: boolean; emptyTitle?: string; emptyDetail?: string; emptyAction?: React.ReactNode }) {
  if (!orders.length) return <EmptyState title={emptyTitle} detail={emptyDetail} action={emptyAction} />;
  return <div className={compact ? 'buyer-order-list compact' : 'buyer-order-list'}>{orders.map(order => <article className="buyer-order-card" key={order.id} aria-label={`Pesanan ${order.orderNo}`}>
    <header>
      <div><small>{new Date(order.neededDate).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' })}</small><h3>{order.kitchen}</h3><small className="buyer-order-number">{order.orderNo}</small></div>
      <div className="order-states"><span className="order-state">{statusLabel[order.status] || order.status}</span></div>
    </header>
    <div className="buyer-order-lines">{order.items.map(item => <div key={item.id}><span><strong>{item.name}</strong></span><b>{item.quantity} {item.orderUnit}{item.actualWeightKg != null ? ` · ${item.actualWeightKg} kg` : ''}</b></div>)}</div>
    <footer><span>{order.items.length} item · {money(Number(order.currentTotal ?? order.finalTotal ?? order.estimatedTotal))}</span>{order.status === 'AWAITING_KITCHEN' && <button className="primary" onClick={() => confirm([order.id])}>Konfirmasi diterima</button>}</footer>
  </article>)}</div>;
}

function Metric({ label, value, note, icon }: { label: string; value: number; note: string; icon: React.ReactNode }) { return <article className="buyer-metric"><div><span>{label}</span><i>{icon}</i></div><strong>{value}</strong><small>{note}</small></article> }
function PageHeading({ title, action, className = '' }: { title: string; action?: React.ReactNode; className?: string }) { return <div className={`page-heading ${className}`.trim()}><h1>{title}</h1>{action}</div> }
function EmptyState({ title, detail, action }: { title: string; detail: string; action?: React.ReactNode }) { return <div className="empty-state"><Package size={24} /><strong>{title}</strong><span>{detail}</span>{action}</div> }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) close() }}><section className="modal-card" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button aria-label="Tutup" onClick={close}><X size={20} /></button></header><div>{children}</div></section></div> }
