import {useEffect,useState,type FormEvent} from 'react';
import {api} from './api';
const phrase='Ya, Saya Yakin Untuk Hapus Semua Data.';
export function ResetData(){
  const[summary,setSummary]=useState<{enabled:boolean;counts:Record<string,number>}|null>(null);const[text,setText]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
  const load=()=>api<{enabled:boolean;counts:Record<string,number>}>('/management/reset').then(setSummary);
  useEffect(()=>{load().catch(error=>setMessage(error.message))},[]);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(busy||text!==phrase)return;setBusy(true);setMessage('');try{const result=await api<{backupId:string}>('/management/reset',{method:'POST',body:JSON.stringify({confirmation:text,password})});setMessage('Data operasional berhasil dibersihkan. Backup tersimpan: '+result.backupId);setText('');setPassword('');await load()}catch(error){setMessage((error as Error).message)}finally{setBusy(false)}};
  return <div className="settings-page"><section className="panel reset-panel"><div className="reset-heading"><h2>Reset data operasional</h2><p>Hapus transaksi, stok, vendor, akun admin dan dapur, serta pembagian dapur.</p><small>Akun superadmin dan Produk Pokok tetap disimpan. Backup dibuat otomatis.</small></div>{summary&&<div className="reset-counts">{Object.entries(summary.counts).map(([name,count])=><span key={name}><b>{count}</b> {name}</span>)}</div>}{message&&<p role="status" className="notice">{message}</p>}{summary?.enabled?<form onSubmit={submit} className="request-form"><label>Password superadmin<input type="password" autoComplete="current-password" required value={password} disabled={busy} onChange={e=>setPassword(e.target.value)}/></label><label>Ketik persis: <strong>{phrase}</strong><input autoComplete="off" spellCheck={false} required value={text} disabled={busy} onChange={e=>setText(e.target.value)}/></label><button className="reset-submit" disabled={busy||text!==phrase||!password}>{busy?'Membuat backup dan membersihkan data…':'Hapus seluruh data operasional'}</button></form>:summary&&<p className="reset-disabled">Reset data dinonaktifkan pada server.</p>}</section></div>
}
