import {useEffect,useRef,useState,type FormEvent} from 'react';
import {X} from 'lucide-react';
import {api} from './api';
import './account-settings.css';

type Batch={id:string;source:'COOPERATIVE'|'VENDOR';vendor:string|null;quantityAvailable:string|number;quantityReserved:string|number;receivedAt:string};
type Stock={id:string;name:string;priceUnit:string;salePrice:string|number;batches:Batch[]};
export function StockEditor({product,onClose,onSaved}:{product:{id:string;name:string;priceUnit:string};onClose:()=>void;onSaved:()=>Promise<unknown>}){
  const[data,setData]=useState<Stock|null>(null);const[price,setPrice]=useState('');const[quantities,setQuantities]=useState<Record<string,string>>({});const[note,setNote]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState<'loading'|'saving'|null>('loading');
  const dialog=useRef<HTMLElement>(null);const alive=useRef(true);
  const load=async()=>{setBusy('loading');setError('');try{const result=await api<Stock>(`/admin-products/${product.id}/stock`);if(!alive.current)return;setData(result);setPrice(String(result.salePrice));setQuantities(Object.fromEntries(result.batches.map(row=>[row.id,String(row.quantityAvailable)])))}catch(reason){if(alive.current)setError((reason as Error).message)}finally{if(alive.current)setBusy(null)}};
  useEffect(()=>{alive.current=true;void load();const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.querySelector<HTMLButtonElement>('button')?.focus();return()=>{alive.current=false;document.body.style.overflow=overflow;previous?.focus()}},[]);
  const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(busy||!data)return;setBusy('saving');setError('');try{await api(`/admin-products/${product.id}/stock`,{method:'PATCH',body:JSON.stringify({salePrice:price,expectedSalePrice:data.salePrice,adjustments:data.batches.filter(row=>Number(quantities[row.id])!==Number(row.quantityAvailable)).map(row=>({batchId:row.id,quantity:quantities[row.id],expectedQuantity:row.quantityAvailable})),...(note.trim()?{note:note.trim()}:{})})});await onSaved();onClose()}catch(reason){if(alive.current)setError((reason as Error).message)}finally{if(alive.current)setBusy(null)}};
  return <div className="account-editor-backdrop"><section ref={dialog} className="account-editor stock-editor" role="dialog" aria-modal="true" aria-labelledby="stock-edit-title" onKeyDown={event=>{if(event.key==='Escape'&&busy!=='saving'){event.preventDefault();onClose()}if(event.key==='Tab'){const nodes=Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea:not(:disabled)'));const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}}}>
    <header><div><h2 id="stock-edit-title">Edit stok</h2><p>{product.name}</p></div><button type="button" aria-label="Tutup edit stok" disabled={busy==='saving'} onClick={onClose}><X size={18}/></button></header>
    <form onSubmit={save}><fieldset className="account-editor-fields" disabled={!!busy}>
      {error&&<div className="account-error" role="alert">{error}</div>}
      {busy==='loading'?<p role="status">Memuat stok…</p>:data&&<>
        <section className="account-section"><label>Harga jual per {product.priceUnit}<input name="salePrice" type="number" min="0" max="999999999999.99" step="0.01" required value={price} onChange={event=>setPrice(event.target.value)}/></label></section>
        <section className="account-section"><h3>Stok tersedia</h3><p className="account-hint">Jumlah di bawah adalah stok bebas. Stok yang sudah dipesan tidak ikut diubah.</p><div className="stock-edit-batches">{data.batches.map(batch=><article className="stock-edit-batch" key={batch.id}><div><strong>{batch.source==='COOPERATIVE'?'Koperasi':batch.vendor||'Vendor'}</strong><small>Masuk {new Date(batch.receivedAt).toLocaleDateString('id-ID')}</small><small>Dipesan: {Number(batch.quantityReserved).toLocaleString('id-ID')} {product.priceUnit}</small></div><label>Jumlah tersedia ({product.priceUnit})<input name={`quantity-${batch.id}`} type="number" min="0" max="99999999999.999" step="0.001" required value={quantities[batch.id]??''} onChange={event=>setQuantities(current=>({...current,[batch.id]:event.target.value}))}/></label></article>)}</div>{!data.batches.length&&<p className="account-hint">Belum ada batch stok. Gunakan Tambah stok untuk persediaan pertama.</p>}</section>
        <section className="account-section"><label>Catatan perubahan<textarea name="note" rows={2} maxLength={200} minLength={3} value={note} onChange={event=>setNote(event.target.value)} placeholder="Contoh: koreksi hasil pengecekan stok"/></label></section>
      </>}
    </fieldset><footer><button type="button" disabled={busy==='saving'} onClick={onClose}>Batal</button>{error&&<button type="button" disabled={!!busy} onClick={()=>void load()}>Muat ulang</button>}<button className="primary" disabled={!!busy||!data}>{busy==='saving'?'Menyimpan…':'Simpan perubahan'}</button></footer></form>
  </section></div>;
}
