import { useEffect,useState,type FormEvent } from 'react';
import { AlertTriangle,Building2,CheckCircle2,CircleDollarSign,ClipboardList,History,MapPin,ShieldCheck,UsersRound } from 'lucide-react';
import { api,download,type User } from './api';

type Summary={activeAdmins:number;activeKitchens:number;activeOrders:number;completedThisMonth:number;salesThisMonth:number;unassignedKitchens:number};
type AdminPerformance={id:string;name:string;email:string;active:boolean;kitchens:number;products:number;activeOrders:number;salesThisMonth:number};
type Overview={summary:Summary;statuses:{status:string;count:number}[];admins:AdminPerformance[]};
type ManagedUser={id:string;name:string;email:string;role:'SUPERADMIN'|'ADMIN'|'BUYER';active:boolean;organizationId:string;organization:string;phone:string|null;address:string|null;gmapsUrl:string|null;managerId:string|null;manager:string|null};
type Kitchen={id:string;name:string;phone:string|null;address:string|null;gmapsUrl:string|null;active:boolean;managerId:string|null;manager:string|null};
type Cluster={adminId:string;admin:string;email:string;active:boolean;kitchens:Kitchen[]};
type OrderItem={id:string;name:string;quantity:number;orderUnit:string;actualWeightKg:number|null};
type Order={id:string;orderNo:string;status:string;neededDate:string;kitchen:string;estimatedTotal:number;finalTotal:number|null;items:OrderItem[]};
type Organization={id:string;type:'COOPERATIVE'|'KITCHEN';name:string;phone:string|null;address:string|null;gmapsUrl:string|null;active:boolean;userCount:number;managerId:string|null;manager:string|null};
type AuditLog={id:string;action:string;entityType:string;entityId:string|null;changes:Record<string,unknown>;createdAt:string;actor:string|null;actorEmail:string|null};
type ProductTemplate={id:string;sku:string;name:string;category:string;image:string|null;orderUnit:string;priceUnit:string;weighingRequired:boolean;estimatedKgPerUnit:number|null;active:boolean};

const money=(value:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value);
const statusLabel:Record<string,string>={SUBMITTED:'Pesanan masuk',PREPARING:'Disiapkan',SHIPPED:'Dalam pengiriman',AWAITING_KITCHEN:'Menunggu dapur',COMPLETED:'Selesai',CANCELLED:'Dibatalkan'};

export function SuperadminPanel({page,currentUser}:{page:string;currentUser:User}){
  const[overview,setOverview]=useState<Overview|null>(null);const[users,setUsers]=useState<ManagedUser[]>([]);const[clusters,setClusters]=useState<Cluster[]>([]);const[kitchens,setKitchens]=useState<Kitchen[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[organizations,setOrganizations]=useState<Organization[]>([]);const[auditLogs,setAuditLogs]=useState<AuditLog[]>([]);const[templates,setTemplates]=useState<ProductTemplate[]>([]);const[error,setError]=useState('');
  const load=async()=>{setError('');try{const[dataOverview,dataUsers,dataClusters,dataKitchens,dataOrders,dataOrganizations,dataAuditLogs,dataTemplates]=await Promise.all([api<Overview>('/management/overview'),api<ManagedUser[]>('/users'),api<Cluster[]>('/clusters'),api<Kitchen[]>('/kitchens'),api<Order[]>('/orders'),api<Organization[]>('/organizations'),api<AuditLog[]>('/audit-logs'),api<ProductTemplate[]>('/templates')]);setOverview(dataOverview);setUsers(dataUsers);setClusters(dataClusters);setKitchens(dataKitchens);setOrders(dataOrders);setOrganizations(dataOrganizations);setAuditLogs(dataAuditLogs);setTemplates(dataTemplates)}catch(reason){setError((reason as Error).message)}};
  useEffect(()=>{load()},[]);
  if(error)return <ManagementPage title="Dashboard Perusahaan" subtitle="Pusat kendali operasional Koperasi Borneo Mandiri"><div className="management-alert error">{error}<button onClick={load}>Coba lagi</button></div></ManagementPage>;
  if(!overview)return <div className="management-loading">Memuat data perusahaan…</div>;
  if(page==='users')return <UserManagement users={users} admins={users.filter(user=>user.role==='ADMIN')} currentUser={currentUser} reload={load}/>;
  if(page==='products')return <ProductMaster templates={templates} reload={load}/>;
  if(page==='clusters')return <ClusterManagement clusters={clusters} kitchens={kitchens} reload={load}/>;
  if(page==='organizations')return <OrganizationDirectory organizations={organizations}/>;
  if(page==='orders')return <AllOrders orders={orders}/>;
  if(page==='audit')return <AuditActivity logs={auditLogs}/>;
  if(page==='reports')return <ManagementReports/>;
  return <ExecutiveDashboard overview={overview} auditLogs={auditLogs}/>;
}

function ExecutiveDashboard({overview,auditLogs}:{overview:Overview;auditLogs:AuditLog[]}){
  const summary=overview.summary;const statusMap=Object.fromEntries(overview.statuses.map(row=>[row.status,row.count]));
  return <ManagementPage title="Dashboard Perusahaan" subtitle="Ringkasan kinerja dan aktivitas seluruh jaringan koperasi.">
    {Number(summary.unassignedKitchens)>0&&<div className="management-alert"><AlertTriangle size={18}/><span><strong>{summary.unassignedKitchens} dapur belum memiliki admin pengelola.</strong> Atur melalui menu Cluster Admin–Dapur.</span></div>}
    <section className="executive-metrics" aria-label="Indikator utama perusahaan">
      <ExecutiveMetric icon={<CircleDollarSign/>} label="Penjualan bulan ini" value={money(Number(summary.salesThisMonth))} note="Pesanan yang telah selesai"/>
      <ExecutiveMetric icon={<ClipboardList/>} label="Pesanan aktif" value={summary.activeOrders} note="Lintas seluruh cluster"/>
      <ExecutiveMetric icon={<CheckCircle2/>} label="Selesai bulan ini" value={summary.completedThisMonth} note="Sudah dikonfirmasi dapur"/>
      <ExecutiveMetric icon={<Building2/>} label="Dapur aktif" value={summary.activeKitchens} note={`${summary.activeAdmins} admin koperasi aktif`}/>
    </section>
    <div className="management-grid">
      <section className="panel management-table-panel"><div className="panel-heading"><div><h2>Kinerja admin koperasi</h2><p>Cakupan cluster dan aktivitas bulan berjalan.</p></div></div><div className="table-scroll"><table className="management-table"><thead><tr><th>Admin</th><th>Dapur</th><th>Produk</th><th>Pesanan aktif</th><th>Penjualan bulan ini</th></tr></thead><tbody>{overview.admins.map(admin=><tr key={admin.id}><td><strong>{admin.name}</strong><small>{admin.email}</small></td><td>{admin.kitchens}</td><td>{admin.products}</td><td>{admin.activeOrders}</td><td>{money(Number(admin.salesThisMonth))}</td></tr>)}</tbody></table></div></section>
      <section className="panel pipeline-panel"><div className="panel-heading"><div><h2>Status operasional</h2><p>Distribusi seluruh pesanan.</p></div></div><div className="pipeline-list">{Object.entries(statusLabel).map(([status,label])=><div key={status}><span>{label}</span><strong>{statusMap[status]||0}</strong></div>)}</div></section>
    </div>
    <section className="panel recent-audit"><div className="panel-heading"><div><h2>Aktivitas manajerial terbaru</h2><p>Perubahan pengguna dan cluster yang tercatat pada sistem.</p></div></div><AuditRows logs={auditLogs.slice(0,5)}/></section>
  </ManagementPage>
}

function ExecutiveMetric({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string|number;note:string}){return <article className="executive-metric"><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}

function UserManagement({users,admins,currentUser,reload}:{users:ManagedUser[];admins:ManagedUser[];currentUser:User;reload:()=>Promise<void>}){
  const[role,setRole]=useState<'ADMIN'|'BUYER'>('BUYER');const[notice,setNotice]=useState('');const[saving,setSaving]=useState(false);
  const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);setNotice('');const form=event.currentTarget;const data=new FormData(form);const body=role==='ADMIN'?{role,fullName:data.get('fullName'),email:data.get('email'),password:data.get('password')}:{role,fullName:data.get('fullName'),email:data.get('email'),password:data.get('password'),kitchen:{name:data.get('kitchenName'),phone:data.get('phone'),address:data.get('address'),gmapsUrl:data.get('gmapsUrl'),adminId:data.get('adminId')||null}};try{await api('/users',{method:'POST',body:JSON.stringify(body)});setNotice('Akun berhasil dibuat dan siap digunakan.');form.reset();setRole('BUYER');await reload()}catch(reason){setNotice((reason as Error).message)}finally{setSaving(false)}};
  const update=async(id:string,changes:Record<string,unknown>)=>{setNotice('');try{await api(`/users/${id}`,{method:'PATCH',body:JSON.stringify(changes)});setNotice('Perubahan akun berhasil disimpan.');await reload()}catch(reason){setNotice((reason as Error).message)}};
  return <ManagementPage title="Manajemen Pengguna" subtitle="Buat akun admin koperasi dan dapur, serta kendalikan akses pengguna.">
    {notice&&<div className="management-alert" role="status">{notice}</div>}
    <div className="account-layout">
      <form className="panel account-form" onSubmit={create}><div className="panel-heading"><div><h2>Buat akun baru</h2><p>Semua bidang bertanda * wajib diisi.</p></div></div><div className="role-switch" aria-label="Pilih jenis akun"><button type="button" className={role==='BUYER'?'active':''} onClick={()=>setRole('BUYER')}>Buyer / Dapur</button><button type="button" className={role==='ADMIN'?'active':''} onClick={()=>setRole('ADMIN')}>Admin Koperasi</button></div><div className="form-grid"><label>Nama pengguna *<input name="fullName" required minLength={2}/></label><label>Email *<input name="email" type="email" autoComplete="off" required/></label><label>Password awal *<input name="password" type="password" minLength={8} defaultValue="Demo123!" required/></label>{role==='BUYER'&&<><label>Nama dapur *<input name="kitchenName" required/></label><label>Nomor HP *<input name="phone" type="tel" required/></label><label>Admin pengelola<select name="adminId"><option value="">Belum ditentukan</option>{admins.filter(admin=>admin.active).map(admin=><option value={admin.id} key={admin.id}>{admin.name}</option>)}</select></label><label className="form-span">Alamat dapur *<textarea name="address" rows={3} required/></label><label className="form-span">Link Google Maps *<input name="gmapsUrl" type="url" placeholder="https://maps.google.com/..." required/></label></>}</div><button className="primary" disabled={saving}>{saving?'Menyimpan…':`Buat akun ${role==='BUYER'?'dapur':'admin'}`}</button></form>
      <aside className="panel account-summary"><ShieldCheck size={26}/><h2>Akses terkontrol</h2><p>Akun buyer hanya melihat katalog dan pesanan dapurnya. Admin koperasi hanya mengelola dapur di dalam cluster yang ditetapkan.</p><dl><div><dt>Superadmin</dt><dd>{users.filter(user=>user.role==='SUPERADMIN'&&user.active).length}</dd></div><div><dt>Admin aktif</dt><dd>{users.filter(user=>user.role==='ADMIN'&&user.active).length}</dd></div><div><dt>Buyer aktif</dt><dd>{users.filter(user=>user.role==='BUYER'&&user.active).length}</dd></div></dl></aside>
    </div>
    <section className="panel management-table-panel"><div className="panel-heading"><div><h2>Daftar pengguna</h2><p>{users.length} akun terdaftar pada sistem.</p></div></div><div className="table-scroll"><table className="management-table"><thead><tr><th>Pengguna</th><th>Role</th><th>Organisasi</th><th>Pengelola</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><strong>{user.name}</strong><small>{user.email}</small></td><td>{user.role==='BUYER'?<span className="role-label">Buyer</span>:<select className="inline-select" value={user.role} disabled={user.id===currentUser.id} onChange={event=>update(user.id,{role:event.target.value})}><option value="ADMIN">Admin</option><option value="SUPERADMIN">Superadmin</option></select>}</td><td>{user.organization||'—'}</td><td>{user.manager||'—'}</td><td><span className={user.active?'state-text active':'state-text'}>{user.active?'Aktif':'Nonaktif'}</span></td><td><button type="button" className="table-action" disabled={user.id===currentUser.id} onClick={()=>update(user.id,{active:!user.active})}>{user.active?'Nonaktifkan':'Aktifkan'}</button></td></tr>)}</tbody></table></div></section>
  </ManagementPage>
}

function ProductMaster({templates,reload}:{templates:ProductTemplate[];reload:()=>Promise<void>}){
  const[weighing,setWeighing]=useState(false);const[notice,setNotice]=useState('');const[saving,setSaving]=useState(false);
  const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);setNotice('');const form=event.currentTarget;const data=new FormData(form);try{await api('/templates',{method:'POST',body:JSON.stringify({name:data.get('name'),category:data.get('category'),image:data.get('image')||null,orderUnit:data.get('orderUnit'),priceUnit:data.get('priceUnit'),weighingRequired:weighing,estimatedKgPerUnit:weighing?data.get('estimatedKgPerUnit'):null})});setNotice('Produk Pokok berhasil ditambahkan.');form.reset();setWeighing(false);await reload()}catch(reason){setNotice((reason as Error).message)}finally{setSaving(false)}};
  const toggle=async(template:ProductTemplate)=>{setNotice('');try{await api(`/templates/${template.id}`,{method:'PATCH',body:JSON.stringify({active:!template.active})});setNotice(`${template.name} ${template.active?'dinonaktifkan':'diaktifkan'}.`);await reload()}catch(reason){setNotice((reason as Error).message)}};
  return <ManagementPage title="Produk Pokok" subtitle="Produk standar yang tersedia untuk seluruh Admin Koperasi.">{notice&&<div className="management-alert" role="status">{notice}</div>}<div className="product-master-layout"><form className="panel master-product-form" onSubmit={create}><div className="panel-heading"><h2>Tambah Produk Pokok</h2></div><div className="form-grid"><label>Nama barang *<input name="name" required minLength={2}/></label><label>Kategori *<input name="category" required placeholder="Bahan Pokok"/></label><label>Satuan pemesanan *<input name="orderUnit" required placeholder="kg, pcs, potong, dus"/></label><label>Satuan harga & stok *<input name="priceUnit" required placeholder="kg, dus" defaultValue="kg"/></label><label className="form-span">Path gambar produk<input name="image" placeholder="/assets/produk/beras.jpg"/></label></div><label className="weighing-toggle"><input type="checkbox" checked={weighing} onChange={event=>setWeighing(event.target.checked)}/><span><strong>Konversi berat</strong><small>Untuk produk yang dipesan per pcs atau potong dan dihargai per kg.</small></span></label>{weighing&&<label className="estimated-weight">Estimasi kilogram per satuan *<input name="estimatedKgPerUnit" type="number" min="0.001" step="0.001" required/></label>}<button className="primary" disabled={saving}>{saving?'Menyimpan…':'Tambah Produk Pokok'}</button></form><aside className="panel master-policy"><ShieldCheck size={26}/><h2>Tersedia untuk semua admin</h2><dl><div><dt>Aktif</dt><dd>{templates.filter(item=>item.active).length}</dd></div><div><dt>Nonaktif</dt><dd>{templates.filter(item=>!item.active).length}</dd></div></dl></aside></div><section className="panel management-table-panel"><div className="panel-heading"><div><h2>Daftar Produk Pokok</h2><p>{templates.length} produk terdaftar.</p></div></div><div className="table-scroll"><table className="management-table product-master-table"><thead><tr><th>Produk</th><th>Kategori</th><th>Satuan pesan</th><th>Satuan stok/harga</th><th>Perlakuan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{templates.map(template=><tr key={template.id}><td><span className="template-product">{template.image?<img src={template.image} alt=""/>:<span/>}<span><strong>{template.name}</strong><small>{template.sku}</small></span></span></td><td>{template.category}</td><td>{template.orderUnit}</td><td>{template.priceUnit}</td><td>{template.weighingRequired?`Timbang · ± ${template.estimatedKgPerUnit} kg`:'Normal'}</td><td><span className={template.active?'state-text active':'state-text'}>{template.active?'Aktif':'Nonaktif'}</span></td><td><button className="table-action" type="button" onClick={()=>toggle(template)}>{template.active?'Nonaktifkan':'Aktifkan'}</button></td></tr>)}</tbody></table></div></section></ManagementPage>
}

function ClusterManagement({clusters,kitchens,reload}:{clusters:Cluster[];kitchens:Kitchen[];reload:()=>Promise<void>}){
  const[selected,setSelected]=useState<Record<string,string[]>>({});const[notice,setNotice]=useState('');const[saving,setSaving]=useState('');
  useEffect(()=>{setSelected(Object.fromEntries(clusters.map(cluster=>[cluster.adminId,cluster.kitchens.map(kitchen=>kitchen.id)])))},[clusters]);
  const toggle=(adminId:string,kitchenId:string,checked:boolean)=>setSelected(current=>({...current,[adminId]:checked?[...(current[adminId]||[]),kitchenId]:(current[adminId]||[]).filter(id=>id!==kitchenId)}));
  const save=async(adminId:string)=>{setSaving(adminId);setNotice('');try{await api(`/clusters/${adminId}/kitchens`,{method:'PUT',body:JSON.stringify({kitchenIds:[...new Set(selected[adminId]||[])]})});setNotice('Cluster berhasil diperbarui.');await reload()}catch(reason){setNotice((reason as Error).message)}finally{setSaving('')}};
  return <ManagementPage title="Cluster Admin–Dapur" subtitle="Tentukan admin koperasi yang bertanggung jawab atas setiap dapur.">
    {notice&&<div className="management-alert" role="status">{notice}</div>}<p className="cluster-note">Satu dapur hanya dapat dikelola oleh satu admin. Memilih dapur yang sudah memiliki pengelola akan memindahkan tanggung jawabnya.</p>
    <div className="cluster-management-grid">{clusters.map(cluster=><article className="panel cluster-manager" key={cluster.adminId}><div className="cluster-manager-head"><div><h2>{cluster.admin}</h2><p>{cluster.email}</p></div><span>{(selected[cluster.adminId]||[]).length} dapur</span></div><div className="kitchen-checks">{kitchens.map(kitchen=><label key={kitchen.id}><input type="checkbox" checked={(selected[cluster.adminId]||[]).includes(kitchen.id)} onChange={event=>toggle(cluster.adminId,kitchen.id,event.target.checked)}/><span><strong>{kitchen.name}</strong><small>{kitchen.managerId&&kitchen.managerId!==cluster.adminId?`Saat ini: ${kitchen.manager}`:kitchen.address}</small></span></label>)}</div><button className="primary" disabled={saving===cluster.adminId} onClick={()=>save(cluster.adminId)}>{saving===cluster.adminId?'Menyimpan…':'Simpan cluster'}</button></article>)}</div>
  </ManagementPage>
}

function OrganizationDirectory({organizations}:{organizations:Organization[]}){
  const cooperative=organizations.find(item=>item.type==='COOPERATIVE');const kitchens=organizations.filter(item=>item.type==='KITCHEN');
  return <ManagementPage title="Direktori Organisasi" subtitle="Identitas koperasi dan seluruh dapur mitra dalam jaringan.">
    <section className="organization-summary"><article className="panel organization-primary"><Building2/><div><span>Koperasi induk</span><h2>{cooperative?.name||'Koperasi Borneo Mandiri'}</h2><p>{cooperative?.address||'Desa Lumbang, Sambas, Kalimantan Barat'}</p></div></article><article className="panel organization-count"><strong>{kitchens.length}</strong><span>Dapur mitra</span><small>{kitchens.filter(item=>item.active).length} organisasi aktif</small></article></section>
    <section className="panel management-table-panel"><div className="panel-heading"><div><h2>Dapur mitra</h2><p>Informasi pengelola dan kontak setiap organisasi.</p></div></div><div className="table-scroll"><table className="management-table"><thead><tr><th>Organisasi</th><th>Admin pengelola</th><th>Kontak</th><th>Alamat</th><th>Status</th></tr></thead><tbody>{kitchens.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small>{item.userCount} akun</small></td><td>{item.manager||'Belum ditentukan'}</td><td>{item.phone||'—'}</td><td><span className="address-cell">{item.address||'—'}{item.gmapsUrl&&<a href={item.gmapsUrl} target="_blank" rel="noreferrer"><MapPin size={13}/>Peta</a>}</span></td><td><span className={item.active?'state-text active':'state-text'}>{item.active?'Aktif':'Nonaktif'}</span></td></tr>)}</tbody></table></div></section>
  </ManagementPage>
}

function AuditActivity({logs}:{logs:AuditLog[]}){return <ManagementPage title="Audit Aktivitas" subtitle="Riwayat perubahan penting yang dilakukan oleh pengguna berwenang."><section className="panel audit-panel"><div className="panel-heading"><div><h2>Aktivitas terbaru</h2><p>{logs.length} aktivitas terakhir ditampilkan.</p></div><History size={20}/></div><AuditRows logs={logs}/></section></ManagementPage>}

function AuditRows({logs}:{logs:AuditLog[]}){const action:Record<string,string>={CREATE:'Membuat',UPDATE:'Memperbarui',ASSIGN:'Mengatur'};const entity:Record<string,string>={USER:'pengguna',PARTNER:'akun mitra',ADMIN_CLUSTER:'cluster admin–dapur'};return <div className="audit-list">{logs.map(log=><article key={log.id}><span className="audit-mark"><History size={15}/></span><div><strong>{log.actor||'Sistem'} {action[log.action]?.toLowerCase()||log.action.toLowerCase()} {entity[log.entityType]||log.entityType.toLowerCase()}</strong><small>{log.actorEmail||'Aktivitas sistem'} · {new Date(log.createdAt).toLocaleString('id-ID')}</small></div><span>{log.action}</span></article>)}{logs.length===0&&<div className="management-empty">Belum ada aktivitas manajerial yang tercatat.</div>}</div>}

function AllOrders({orders}:{orders:Order[]}){return <ManagementPage title="Semua Pesanan" subtitle="Pantau aktivitas pengadaan dari seluruh dapur dan admin koperasi."><section className="panel management-table-panel"><div className="panel-heading"><div><h2>Riwayat lintas cluster</h2><p>{orders.length} pesanan tercatat.</p></div></div><div className="table-scroll"><table className="management-table"><thead><tr><th>Pesanan</th><th>Dapur</th><th>Dibutuhkan</th><th>Item</th><th>Status</th><th>Nilai</th></tr></thead><tbody>{orders.map(order=><tr key={order.id}><td><strong>{order.orderNo}</strong></td><td>{order.kitchen}</td><td>{new Date(order.neededDate).toLocaleDateString('id-ID')}</td><td>{order.items.length} jenis</td><td><span className="state-text active">{statusLabel[order.status]}</span></td><td>{money(Number(order.finalTotal??order.estimatedTotal))}</td></tr>)}</tbody></table></div>{orders.length===0&&<div className="management-empty">Belum ada pesanan pada sistem.</div>}</section></ManagementPage>}

function ManagementReports(){const[error,setError]=useState('');const get=async(type:'pdf'|'xls')=>{try{setError('');await download(`/reports/sales.${type}`,`laporan-penjualan.${type}`)}catch(reason){setError((reason as Error).message)}};return <ManagementPage title="Laporan Perusahaan" subtitle="Ekspor laporan operasional dan keuangan seluruh cluster."><section className="panel management-report"><div><h2>Laporan penjualan konsolidasi</h2><p>PDF untuk laporan operasional. Excel berisi tabel keuangan yang siap diolah.</p>{error&&<span className="form-error">{error}</span>}</div><div><button onClick={()=>get('pdf')}>Unduh PDF</button><button className="primary" onClick={()=>get('xls')}>Unduh Excel</button></div></section></ManagementPage>}

function ManagementPage({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="management-page"><header className="management-title"><div><span>Manajemen Perusahaan</span><h1>{title}</h1><p>{subtitle}</p></div><UsersRound size={30}/></header>{children}</div>}
