import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {readFileSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
import {mkdtemp,rm,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import pg from 'pg';
import bcrypt from 'bcryptjs';
import sharp from 'sharp';
import {apiDirectory,maintenancePool,maintenanceUrl} from './maintenance.js';

// All fixtures and destructive tests are confined to a uniquely created scratch DB.
const database=`borneo_security_test_${randomUUID().replaceAll('-','')}`;
if(!/^borneo_security_test_[a-f0-9]{32}$/.test(database))throw new Error('Invalid scratch DB name');
const owner=maintenancePool();
const ownerUrl=new URL(maintenanceUrl());ownerUrl.pathname=`/${database}`;
const imageTestDirectory=await mkdtemp(join(tmpdir(),'borneo-private-images-test-'));
process.env.PRODUCT_STORAGE_DIR=imageTestDirectory;
let fixture:pg.Pool|undefined;
let app:Awaited<ReturnType<typeof import('../server.js').buildApp>>|undefined;
let runtime:pg.Pool|undefined;
let created=false;
const cleanupRole=`borneo_cleanup_test_${randomUUID().replaceAll('-','')}`;
let cleanupRoleCreated=false;
let checks=0;
function check(name:string){checks++;console.log(`PASS ${name}`);}
try{
  await owner.query(`CREATE DATABASE "${database}"`);created=true;
  fixture=new pg.Pool({connectionString:ownerUrl.toString()});
  const migrations=join(apiDirectory,'src/database/migrations');
  for(const file of readdirSync(migrations).filter(file=>file.endsWith('.sql')).sort())await fixture.query(readFileSync(join(migrations,file),'utf8'));
  // Exercise APIs with the same restricted role used by the local running server.
  const runtimeUrl=new URL(readFileSync(join(apiDirectory,'.env.runtime'),'utf8').match(/^DATABASE_URL=(.*)$/m)![1].trim());
  runtimeUrl.pathname=`/${database}`;
  await fixture.query('REVOKE CREATE ON SCHEMA public FROM PUBLIC');
  await fixture.query('GRANT USAGE ON SCHEMA public TO borneo_runtime');
  await fixture.query('GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO borneo_runtime');
  await fixture.query('REVOKE UPDATE,DELETE ON audit_logs,order_status_history,inventory_movements FROM borneo_runtime');
  process.env.NODE_ENV='test';process.env.DATABASE_URL=runtimeUrl.toString();process.env.JWT_SECRET=randomBytes(48).toString('hex');
  process.env.ALLOW_DATA_RESET='false';delete process.env.DATA_RESET_DATABASE_URL;
  const server=await import('../server.js');const client=await import('./client.js');runtime=client.pool;
  await client.assertRuntimeDatabaseRole();check('runtime role cannot own database/schema or bypass security');
  app=await server.buildApp();await app.ready();
  const one=async(sql:string,params:unknown[]=[]) => (await fixture!.query(sql,params)).rows[0];
  const cooperative=await one("INSERT INTO organizations(type,name) VALUES('COOPERATIVE','Test Cooperative') RETURNING id");
  const kitchenA=await one("INSERT INTO organizations(type,name) VALUES('KITCHEN','Kitchen A') RETURNING id");
  const kitchenB=await one("INSERT INTO organizations(type,name) VALUES('KITCHEN','Kitchen B') RETURNING id");
  const password=randomBytes(18).toString('base64url'),hash=await bcrypt.hash(password,4);
  const makeUser=(role:string,email:string,org:string)=>one('INSERT INTO users(organization_id,full_name,email,password_hash,role) VALUES($1,$2,$2,$3,$4) RETURNING id,email',[org,email,hash,role]);
  const sa=await makeUser('SUPERADMIN','sa@test.local',cooperative.id);
  const a=await makeUser('ADMIN','a@test.local',cooperative.id),b=await makeUser('ADMIN','b@test.local',cooperative.id);
  const buyerA=await makeUser('BUYER','buyer-a@test.local',kitchenA.id),buyerB=await makeUser('BUYER','buyer-b@test.local',kitchenB.id);
  await fixture.query('INSERT INTO admin_kitchens(admin_user_id,kitchen_id) VALUES($1,$2),($3,$4)',[a.id,kitchenA.id,b.id,kitchenB.id]);
  const login=async(email:string)=>{const r=await app!.inject({method:'POST',url:'/api/auth/login',payload:{email,password}});assert.equal(r.statusCode,200,r.body);return r.json().token as string;};
  const [ta,tb,tbuyerA,tbuyerB,tsa]=await Promise.all([a,b,buyerA,buyerB,sa].map(u=>login(u.email)));
  const call=(method:'GET'|'POST'|'PATCH'|'PUT'|'DELETE',url:string,token:string,payload?:object)=>app!.inject({method,url,headers:{authorization:`Bearer ${token}`},payload});
  const publicWebsite=await app.inject({method:'GET',url:'/api/website'});
  assert.equal(publicWebsite.statusCode,200,publicWebsite.body);
  assert.deepEqual(publicWebsite.json(),{whatsapp:'',email:'',instagram:'',address:'Sambas, Kalimantan Barat'});
  const websitePayload={whatsapp:'0812 3456 7890',email:'ADMIN@example.com',instagram:'@Borneo.Test',address:'Sambas, Kalimantan Barat'};
  assert.equal((await app.inject({method:'PUT',url:'/api/management/website',payload:websitePayload})).statusCode,401);
  for(const token of [ta,tbuyerA])assert.equal((await call('PUT','/api/management/website',token,websitePayload)).statusCode,403);
  const savedWebsite=await call('PUT','/api/management/website',tsa,websitePayload);
  assert.equal(savedWebsite.statusCode,200,savedWebsite.body);
  const expectedWebsite={...websitePayload,whatsapp:'6281234567890',email:'admin@example.com',instagram:'borneo.test'};
  assert.deepEqual(savedWebsite.json(),expectedWebsite);
  assert.deepEqual((await app.inject({method:'GET',url:'/api/website'})).json(),expectedWebsite);
  assert.equal((await one("SELECT count(*)::int AS n FROM audit_logs WHERE action='UPDATE' AND entity_type='WEBSITE' AND actor_id=$1",[sa.id])).n,1);
  check('website contacts are public, editable only by superadmin, normalized and audited');
  for(const invalid of [{whatsapp:'javascript:alert(1)'},{instagram:'https://evil.example'},{email:'not-an-email'},{address:''},{unexpected:true}]){
    assert.equal((await call('PUT','/api/management/website',tsa,{...websitePayload,...invalid})).statusCode,400);
  }
  assert.deepEqual((await app.inject({method:'GET',url:'/api/website'})).json(),expectedWebsite);
  const clearedWebsite={whatsapp:'',email:'',instagram:'',address:'Sambas, Kalimantan Barat'};
  assert.equal((await call('PUT','/api/management/website',tsa,clearedWebsite)).statusCode,200);
  assert.deepEqual((await app.inject({method:'GET',url:'/api/website'})).json(),clearedWebsite);
  check('website validation rejects unsafe contact values without changes and allows optional contacts');
  const accountPayload={role:'ADMIN',fullName:'Username Only',username:'username.only',password};
  const usernameAccount=await call('POST','/api/users',tsa,accountPayload);
  assert.equal(usernameAccount.statusCode,200,usernameAccount.body);
  assert.equal(usernameAccount.json().email,null);
  const usernameLogin=await app.inject({method:'POST',url:'/api/auth/login',payload:{identifier:'USERNAME.ONLY',password}});
  assert.equal(usernameLogin.statusCode,200,usernameLogin.body);
  assert.equal(usernameLogin.json().user.username,'username.only');
  assert.equal((await call('POST','/api/users',tsa,{...accountPayload,username:'USERNAME.ONLY'})).statusCode,409);
  assert.equal((await call('POST','/api/users',tsa,{...accountPayload,username:'invalid@username'})).statusCode,400);
  const emailLogin=await app.inject({method:'POST',url:'/api/auth/login',payload:{identifier:a.email,password}});
  assert.equal(emailLogin.statusCode,200,emailLogin.body);
  check('username-only accounts, optional email, case-insensitive login and uniqueness');
  assert.equal((await app.inject({method:'GET',url:'/api/orders'})).statusCode,401);
  assert.equal((await call('GET','/api/users',tbuyerA)).statusCode,403);
  assert.equal((await call('GET','/api/reports/sales.pdf',tbuyerA)).statusCode,403);check('anonymous and buyer privilege escalation blocked');
  const template=await one("INSERT INTO product_templates(sku,name,category,order_unit,price_unit,owner_admin_user_id) VALUES('T-A','Private rice','Staples','kg','kg',$1) RETURNING id",[a.id]);
  const product=await one('INSERT INTO admin_products(admin_user_id,template_id,sale_price) VALUES($1,$2,10000) RETURNING id',[a.id,template.id]);
  assert.equal((await call('POST','/api/admin-products',tb,{templateId:template.id,salePrice:1})).statusCode,404);
  await assert.rejects(fixture.query('INSERT INTO admin_products(admin_user_id,template_id,sale_price) VALUES($1,$2,1)',[b.id,template.id]),(e:any)=>e.code==='23514');check('private product cross-tenant access blocked by API and DB');
  assert.equal((await call('POST','/api/stock',ta,{adminProductId:product.id,quantity:100,salePrice:10000,source:'COOPERATIVE'})).statusCode,200);
  assert.equal((await call('POST','/api/stock',tb,{adminProductId:product.id,quantity:10,salePrice:1})).statusCode,404);
  assert.equal((await call('POST','/api/stock',ta,{customProduct:{name:'Bad',category:'Bad',unit:'kg',image:'javascript:alert(1)'},quantity:1,salePrice:10})).statusCode,400);check('stock ownership and image input validation');
  const payload={neededDate:'2026-10-01',idempotencyKey:randomUUID(),items:[{adminProductId:product.id,quantity:10}]};
  assert.equal((await call('POST','/api/orders',tbuyerB,payload)).statusCode,409);
  const duplicates=await Promise.all([call('POST','/api/orders',tbuyerA,payload),call('POST','/api/orders',tbuyerA,payload)]);
  duplicates.forEach(r=>assert.equal(r.statusCode,200,r.body));assert.equal(duplicates[0].json().id,duplicates[1].json().id);
  const id=duplicates[0].json().id;
  assert.equal((await one('SELECT count(*)::int AS n FROM orders')).n,1);
  assert.equal(Number((await one('SELECT quantity_reserved FROM inventory_batches')).quantity_reserved),10);check('concurrent checkout retry reserves once');
  assert.equal((await call('GET','/api/orders',tbuyerB)).json().length,0);
  assert.equal((await call('GET','/api/orders',tb)).json().length,0);
  assert.equal((await call('PATCH',`/api/orders/${id}/status`,tb,{status:'CANCELLED'})).statusCode,404);check('orders isolated across admins and kitchens');
  const allocation=await one('SELECT id FROM order_item_allocations');
  assert.equal((await call('PATCH',`/api/allocations/${allocation.id}/prepared`,ta,{prepared:true})).statusCode,200);
  const ships=await Promise.all([call('PATCH',`/api/orders/${id}/status`,ta,{status:'SHIPPED'}),call('PATCH',`/api/orders/${id}/status`,ta,{status:'SHIPPED'})]);
  assert.deepEqual(ships.map(r=>r.statusCode).sort(),[200,409]);
  assert.equal(Number((await one('SELECT quantity_available FROM inventory_batches')).quantity_available),90);
  assert.equal(Number((await one('SELECT quantity_reserved FROM inventory_batches')).quantity_reserved),0);
  assert.equal((await one("SELECT count(*)::int AS n FROM inventory_movements WHERE movement_type='OUT'")).n,1);check('concurrent shipment cannot subtract stock twice');
  assert.equal((await call('PATCH',`/api/allocations/${allocation.id}/prepared`,ta,{prepared:false})).statusCode,409);
  assert.equal((await call('PATCH',`/api/orders/${id}/status`,ta,{status:'AWAITING_KITCHEN'})).statusCode,200);
  assert.equal((await call('PATCH',`/api/orders/${id}/status`,ta,{status:'COMPLETED'})).statusCode,403);
  assert.equal((await call('PATCH',`/api/orders/${id}/status`,tbuyerA,{status:'COMPLETED'})).statusCode,200);check('post-shipment edits blocked and kitchen confirms receipt');
  const second=await call('POST','/api/orders',tbuyerA,{...payload,idempotencyKey:randomUUID()});assert.equal(second.statusCode,200,second.body);
  const cancels=await Promise.all([call('PATCH',`/api/orders/${second.json().id}/status`,tbuyerA,{status:'CANCELLED'}),call('PATCH',`/api/orders/${second.json().id}/status`,tbuyerA,{status:'CANCELLED'})]);
  assert.deepEqual(cancels.map(r=>r.statusCode).sort(),[200,409]);
  assert.equal(Number((await one('SELECT quantity_available FROM inventory_batches')).quantity_available),90);check('concurrent cancellation releases stock only once');
  assert.equal((await call('GET','/api/reports/sales',tb)).json().length,0);
  assert.equal((await call('GET','/api/reports/sales',ta)).json().length,1);
  assert.equal((await call('GET','/api/reports/sales.pdf',ta)).statusCode,200);
  assert.equal((await call('GET','/api/reports/sales.xls',ta)).statusCode,200);check('reports isolated and PDF/Excel generation works');
  const weightedTemplate=await one("INSERT INTO product_templates(sku,name,category,order_unit,price_unit,weighing_required,estimated_kg_per_unit) VALUES('T-W','Chicken','Protein','potong','kg',true,0.8) RETURNING id");
  const weightedProduct=await one('INSERT INTO admin_products(admin_user_id,template_id,sale_price) VALUES($1,$2,30000) RETURNING id',[a.id,weightedTemplate.id]);
  assert.equal((await call('POST','/api/stock',ta,{adminProductId:weightedProduct.id,quantity:20,salePrice:30000,source:'COOPERATIVE'})).statusCode,200);
  const weighted=await call('POST','/api/orders',tbuyerA,{...payload,idempotencyKey:randomUUID(),items:[{adminProductId:weightedProduct.id,quantity:10}]});
  assert.equal(weighted.statusCode,200,weighted.body);
  const weightedId=weighted.json().id;
  const weightedItem=await one('SELECT id FROM order_items WHERE order_id=$1',[weightedId]);
  const weightedAllocation=await one('SELECT id FROM order_item_allocations WHERE order_item_id=$1',[weightedItem.id]);
  assert.equal((await call('PATCH',`/api/allocations/${weightedAllocation.id}/prepared`,ta,{prepared:true})).statusCode,200);
  assert.equal((await call('PATCH',`/api/orders/${weightedId}/status`,ta,{status:'SHIPPED'})).statusCode,409);
  assert.equal((await call('PATCH',`/api/order-items/${weightedItem.id}/actual-weight`,tb,{actualWeightKg:9})).statusCode,404);
  assert.equal((await call('PATCH',`/api/order-items/${weightedItem.id}/actual-weight`,ta,{actualWeightKg:21})).statusCode,200);
  assert.equal((await call('PATCH',`/api/orders/${weightedId}/status`,ta,{status:'SHIPPED'})).statusCode,409);
  assert.equal(Number((await one('SELECT quantity_reserved FROM inventory_batches WHERE admin_product_id=$1',[weightedProduct.id])).quantity_reserved),8);
  assert.equal((await call('PATCH',`/api/order-items/${weightedItem.id}/actual-weight`,ta,{actualWeightKg:9})).statusCode,200);
  for(const token of [ta,tbuyerA]){
    const response=await call('GET','/api/orders',token);
    assert.equal(response.statusCode,200,response.body);
    const priced=response.json().find((row:any)=>row.id===weightedId);
    assert.equal(Number(priced.currentTotal),270000);
    assert.equal(Number(priced.estimatedTotal),240000);
    assert.equal(priced.finalTotal,null);
    assert.equal(Number(priced.items[0].actualWeightKg),9);
  }
  assert.equal((await call('PATCH',`/api/orders/${weightedId}/status`,ta,{status:'SHIPPED'})).statusCode,200);
  assert.equal(Number((await one('SELECT quantity_available FROM inventory_batches WHERE admin_product_id=$1',[weightedProduct.id])).quantity_available),11);
  assert.equal(Number((await one('SELECT final_total FROM orders WHERE id=$1',[weightedId])).final_total),270000);
  check('actual weight is mandatory, tenant-scoped and stock shortage rolls back atomically');
  const mixed=await call('POST','/api/orders',tbuyerA,{...payload,idempotencyKey:randomUUID(),items:[{adminProductId:weightedProduct.id,quantity:1},{adminProductId:product.id,quantity:1}]});
  assert.equal(mixed.statusCode,200,mixed.body);
  const readMixed=async()=>{const response=await call('GET','/api/orders',ta);assert.equal(response.statusCode,200,response.body);return response.json().find((row:any)=>row.id===mixed.json().id);};
  const before=await readMixed();
  const positions=(row:any)=>row.items.map((item:any)=>({id:item.id,allocations:item.allocations.map((allocation:any)=>allocation.id)}));
  for(const item of before.items){
    for(const allocation of item.allocations){
      assert.equal((await call('PATCH',`/api/allocations/${allocation.id}/prepared`,ta,{prepared:true})).statusCode,200);
      assert.deepEqual(positions(await readMixed()),positions(before));
    }
  }
  assert.equal((await call('PATCH',`/api/orders/${mixed.json().id}/status`,ta,{status:'CANCELLED'})).statusCode,200);
  check('checking mixed order items preserves item and allocation positions');
  const special=await call('POST','/api/special-requests',tbuyerA,{name:'Special flour',quantity:3,unit:'karung'});
  assert.equal(special.statusCode,200,special.body);
  const approval={source:'VENDOR',vendorName:'Test Supplier',unit:'karung',salePrice:200000};
  assert.equal((await call('PATCH',`/api/special-requests/${special.json().id}/approve`,tb,approval)).statusCode,404);
  const approvals=await Promise.all([call('PATCH',`/api/special-requests/${special.json().id}/approve`,ta,approval),call('PATCH',`/api/special-requests/${special.json().id}/approve`,ta,approval)]);
  assert.deepEqual(approvals.map(r=>r.statusCode).sort(),[200,404]);
  const specialOrderId=approvals.find(r=>r.statusCode===200)!.json().orderId;
  const specialAllocation=await one('SELECT a.id FROM order_item_allocations a JOIN order_items i ON i.id=a.order_item_id WHERE i.order_id=$1',[specialOrderId]);
  assert.equal((await call('PATCH',`/api/allocations/${specialAllocation.id}/prepared`,ta,{prepared:true})).statusCode,200);
  assert.equal((await call('PATCH',`/api/orders/${specialOrderId}/status`,ta,{status:'SHIPPED'})).statusCode,200);
  check('special request approval is tenant-scoped, idempotent and vendor order ships');
  const partner=await call('POST','/api/partners',ta,{username:'new.kitchen',name:'New Kitchen',phone:'081234567890',address:'Test street 123',gmapsUrl:'https://maps.google.com/'});
  assert.equal(partner.statusCode,200,partner.body);assert.notEqual(partner.json().temporaryPassword,'Demo123!');assert.ok(partner.json().temporaryPassword.length>=24);check('new partners get unique strong passwords');
  await assert.rejects(runtime.query('DELETE FROM audit_logs'),(e:any)=>e.code==='42501');
  await assert.rejects(runtime.query('CREATE TABLE public.forbidden(id int)'),(e:any)=>e.code==='42501');
  await assert.rejects(fixture.query('UPDATE inventory_batches SET quantity_available=1000'),(e:any)=>e.code==='23514');check('DB blocks audit erasure, DDL and impossible stock');
  assert.equal((await call('POST','/api/management/reset',tsa,{confirmation:'Ya, Saya Yakin Untuk Hapus Semua Data.',password})).statusCode,403);check('reset disabled without explicit maintenance configuration');
  const upload=await sharp({create:{width:64,height:64,channels:4,background:{r:120,g:160,b:200,alpha:0.5}}}).png().toBuffer();
  const imageRequest=(token?:string,payload:Buffer=upload)=>app!.inject({method:'POST',url:'/api/images/convert',headers:{'content-type':'application/octet-stream',...(token?{authorization:`Bearer ${token}`}:{})},payload});
  assert.equal((await imageRequest()).statusCode,401);
  assert.equal((await imageRequest(tbuyerA)).statusCode,403);
  assert.equal((await imageRequest(ta,Buffer.from('<svg/>'))).statusCode,400);
  assert.equal((await imageRequest(ta,Buffer.alloc(8*1024*1024+1))).statusCode,413);
  const converted=await imageRequest(ta);assert.equal(converted.statusCode,200,converted.body);
  assert.match(converted.json().image,/^data:image\/webp;base64,/);
  // Direct uploads cannot bypass server-side re-encoding by calling the catalog API.
  const master=await call('POST','/api/templates',tsa,{name:'Uploaded product',category:'Test',orderUnit:'kg',priceUnit:'kg',image:`data:image/png;base64,${upload.toString('base64')}`});
  assert.equal(master.statusCode,200,master.body);
  const masterImage=(await one('SELECT image_path FROM product_templates WHERE id=$1',[master.json().id])).image_path;
  assert.match(masterImage,/^\/api\/product-images\/produk-pokok\/[a-f0-9-]+\.webp$/);
  assert.equal((await app.inject({method:'GET',url:masterImage})).statusCode,401);
  assert.equal((await app.inject({method:'HEAD',url:masterImage})).statusCode,401);
  assert.equal((await call('GET',masterImage,tbuyerA)).statusCode,404);
  for(const token of [tsa,ta,tb]){
    const image=await call('GET',masterImage,token);assert.equal(image.statusCode,200,image.body);
    assert.equal(image.headers['content-type'],'image/webp');
    assert.equal(image.headers['cache-control'],'private, no-store');
    assert.equal((await sharp(image.rawPayload).metadata()).format,'webp');
  }
  const custom=await call('POST','/api/stock',ta,{customProduct:{name:'Private image product',category:'Test',unit:'kg',image:`data:image/png;base64,${upload.toString('base64')}`},quantity:5,salePrice:10000});
  assert.equal(custom.statusCode,200,custom.body);
  const customImage=(await one("SELECT image_path FROM product_templates WHERE owner_admin_user_id=$1 AND name='Private image product'",[a.id])).image_path;
  assert.match(customImage,/^\/api\/product-images\/produk-tambahan\/[a-f0-9-]+\.webp$/);
  for(const token of [tsa,ta,tbuyerA])assert.equal((await call('GET',customImage,token)).statusCode,200);
  for(const token of [tb,tbuyerB])assert.equal((await call('GET',customImage,token)).statusCode,404);
  assert.equal((await call('POST','/api/templates',tsa,{name:'No path reuse',category:'Test',orderUnit:'kg',priceUnit:'kg',image:customImage})).statusCode,400);
  assert.equal((await call('GET',`/api/product-images/produk-tambahan/${randomUUID()}.webp`,tsa)).statusCode,404);
  assert.equal((await call('GET',customImage.replace('produk-tambahan','produk-pokok'),ta)).statusCode,404);
  check('private WebP files are separated by product kind and enforce login, tenant access and private caching');
  const masterSourcePayload={name:'Master source product',category:'Test',orderUnit:'kg',priceUnit:'kg'};
  const sourceMaster=await call('POST','/api/templates',tsa,masterSourcePayload);
  assert.equal(sourceMaster.statusCode,200,sourceMaster.body);
  const sourceMasterId=sourceMaster.json().id;
  assert.equal(sourceMaster.json().stockSource,'COOPERATIVE');
  const sourceProduct=await one('SELECT id FROM admin_products WHERE template_id=$1 AND admin_user_id=$2',[sourceMasterId,a.id]);
  const stockPayload={adminProductId:sourceProduct.id,quantity:2,salePrice:15000};
  assert.equal((await call('POST','/api/stock',ta,{...stockPayload,source:'VENDOR',vendorName:'Forbidden supplier'})).statusCode,400);
  assert.equal((await one('SELECT count(*)::int AS n FROM inventory_batches WHERE admin_product_id=$1',[sourceProduct.id])).n,0);
  const cooperativeBatch=await call('POST','/api/stock',ta,stockPayload);
  assert.equal(cooperativeBatch.statusCode,200,cooperativeBatch.body);
  assert.equal((await one('SELECT source FROM inventory_batches WHERE id=$1',[cooperativeBatch.json().id])).source,'COOPERATIVE');
  assert.equal((await call('PATCH',`/api/templates/${sourceMasterId}`,ta,{stockSource:'VENDOR'})).statusCode,403);
  const sourceUpdate=await call('PATCH',`/api/templates/${sourceMasterId}`,tsa,{stockSource:'VENDOR'});
  assert.equal(sourceUpdate.statusCode,200,sourceUpdate.body);
  assert.equal(sourceUpdate.json().stockSource,'VENDOR');
  const visibleSource=(await call('GET','/api/catalog',ta)).json().find((row:any)=>row.id===sourceProduct.id);
  assert.equal(visibleSource.stockSource,'VENDOR');assert.equal(visibleSource.isMaster,true);
  assert.equal((await call('POST','/api/stock',ta,{...stockPayload,source:'COOPERATIVE'})).statusCode,400);
  assert.equal((await call('POST','/api/stock',ta,stockPayload)).statusCode,400);
  await assert.rejects(fixture.query("INSERT INTO inventory_batches(admin_product_id,source,quantity_initial,quantity_available,created_by) VALUES($1,'COOPERATIVE',1,1,$2)",[sourceProduct.id,a.id]),(error:any)=>error.code==='23514');
  const vendorBatch=await call('POST','/api/stock',ta,{...stockPayload,vendorName:'Allowed supplier'});
  assert.equal(vendorBatch.statusCode,200,vendorBatch.body);
  assert.equal((await one('SELECT source FROM inventory_batches WHERE id=$1',[vendorBatch.json().id])).source,'VENDOR');
  assert.equal((await one('SELECT source FROM inventory_batches WHERE id=$1',[cooperativeBatch.json().id])).source,'COOPERATIVE');
  const vendorMaster=await call('POST','/api/templates',tsa,{...masterSourcePayload,name:'Vendor master',stockSource:'VENDOR'});
  assert.equal(vendorMaster.statusCode,200,vendorMaster.body);
  assert.equal(vendorMaster.json().stockSource,'VENDOR');
  assert.equal((await call('POST','/api/templates',tsa,{...masterSourcePayload,stockSource:'INVALID'})).statusCode,400);
  assert.equal((await call('PATCH',`/api/templates/${sourceMasterId}`,tsa,{stockSource:'INVALID'})).statusCode,400);
  check('master source controlled by superadmin, enforced by API and DB, vendor names required and old stock preserved');
  assert.equal((await call('GET','/api/accounts',tbuyerA)).statusCode,403);
  assert.equal((await app.inject({method:'GET',url:'/api/accounts'})).statusCode,401);
  const scopedAccounts=(await call('GET','/api/accounts',ta)).json();
  assert.ok(scopedAccounts.some((row:any)=>row.id===buyerA.id));
  assert.ok(!scopedAccounts.some((row:any)=>row.id===buyerB.id||row.id===b.id));
  const managedPassword='ManagedInitial123!';
  const managed=await call('POST','/api/users',tsa,{fullName:'Managed buyer',username:'managed.buyer',password:managedPassword,role:'BUYER',kitchen:{name:'Managed kitchen',phone:'081234567890',address:'Sambas Barat',adminId:a.id}});
  assert.equal(managed.statusCode,200,managed.body);const managedId=managed.json().id;
  const loginManaged=async(identifier:string,password:string)=>{const r=await app!.inject({method:'POST',url:'/api/auth/login',payload:{identifier,password}});assert.equal(r.statusCode,200,r.body);return r.json().token as string};
  const originalManagedToken=await loginManaged('managed.buyer',managedPassword);
  assert.equal((await call('PATCH',`/api/accounts/${managedId}`,tb,{fullName:'Foreign edit'})).statusCode,404);
  assert.equal((await call('PATCH',`/api/accounts/${a.id}`,ta,{fullName:'Self escalation'})).statusCode,404);
  assert.equal((await call('PATCH',`/api/accounts/${managedId}`,ta,{role:'SUPERADMIN'})).statusCode,400);
  assert.equal((await call('PATCH',`/api/accounts/${managedId}`,ta,{kitchen:{adminId:b.id}})).statusCode,403);
  const editedManaged=await call('PATCH',`/api/accounts/${managedId}`,ta,{fullName:'Managed updated',username:'managed.updated',email:'managed@example.com',kitchen:{name:'Managed kitchen updated',phone:'081298765432',address:'Sambas Kalimantan Barat',gmapsUrl:null}});
  assert.equal(editedManaged.statusCode,200,editedManaged.body);
  assert.equal(editedManaged.json().organization,'Managed kitchen updated');assert.equal(editedManaged.json().phone,'081298765432');
  assert.equal((await call('PATCH',`/api/accounts/${managedId}`,ta,{email:sa.email})).statusCode,409);
  assert.equal((await call('PATCH',`/api/accounts/${managedId}`,tsa,{kitchen:{adminId:b.id}})).statusCode,200);
  assert.equal((await call('PATCH',`/api/accounts/${managedId}`,ta,{fullName:'Stale tenant'})).statusCode,404);
  assert.equal((await call('PATCH',`/api/accounts/${managedId}`,tsa,{kitchen:{adminId:a.id}})).statusCode,200);
  const resetPassword='ManagedReset123!';
  assert.equal((await call('PATCH',`/api/accounts/${managedId}`,ta,{password:resetPassword,currentPassword:'WrongPassword123!'})).statusCode,403);
  assert.equal((await call('PATCH',`/api/accounts/${managedId}`,ta,{password:resetPassword,currentPassword:password})).statusCode,200);
  assert.equal((await call('GET','/api/auth/me',originalManagedToken)).statusCode,401);
  const resetToken=await loginManaged('managed.updated',resetPassword);
  assert.equal((await call('PATCH','/api/auth/me',ta,{phone:'081234567890'})).statusCode,403);
  for(const payload of [{fullName:'Forbidden'},{username:'forbidden'},{role:'SUPERADMIN'},{active:false},{phone:'08123456789',kitchen:{address:'Forbidden'}}])assert.equal((await call('PATCH','/api/auth/me',resetToken,payload)).statusCode,400);
  assert.equal((await call('PATCH','/api/auth/me',resetToken,{phone:'081211111111'})).statusCode,200);
  assert.equal((await call('GET','/api/auth/me',resetToken)).json().phone,'081211111111');
  const selfPassword='ManagedSelfChange123!';
  assert.equal((await call('PATCH','/api/auth/me',resetToken,{currentPassword:'WrongPassword123!',newPassword:selfPassword})).statusCode,403);
  assert.equal((await call('PATCH','/api/auth/me',resetToken,{currentPassword:resetPassword,newPassword:selfPassword})).statusCode,200);
  assert.equal((await call('GET','/api/auth/me',resetToken)).statusCode,401);
  assert.equal((await call('GET','/api/auth/me',await loginManaged('managed.updated',selfPassword))).statusCode,200);
  const accountAudits=(await fixture.query('SELECT changes FROM audit_logs WHERE entity_id=$1',[managedId])).rows;
  for(const secret of [managedPassword,resetPassword,selfPassword,password])assert.ok(!JSON.stringify(accountAudits).includes(secret));
  assert.equal((await call('PATCH',`/api/accounts/${sa.id}`,tsa,{active:false})).statusCode,409);
  check('account management isolated by role and cluster, verified resets revoke sessions, buyer self-service is restricted and passwords never audited');
  const superadminReset='SuperadminReset123!';
  const resetBySuperadmin=await call('PATCH',`/api/accounts/${managedId}`,tsa,{password:superadminReset});
  assert.equal(resetBySuperadmin.statusCode,200,resetBySuperadmin.body);
  assert.equal((await app.inject({method:'POST',url:'/api/auth/login',payload:{identifier:'managed.updated',password:selfPassword}})).statusCode,401);
  assert.equal((await call('DELETE',`/api/accounts/${managedId}`,tsa)).statusCode,409);
  assert.equal((await call('DELETE',`/api/accounts/${managedId}`,ta)).statusCode,403);
  assert.equal((await call('PATCH',`/api/accounts/${managedId}`,tsa,{active:false})).statusCode,200);
  const removeManaged=await call('DELETE',`/api/accounts/${managedId}`,tsa);
  assert.equal(removeManaged.statusCode,200,removeManaged.body);
  assert.ok((await one('SELECT deleted_at FROM users WHERE id=$1',[managedId])).deleted_at);
  assert.ok(!(await call('GET','/api/users',tsa)).json().some((row:any)=>row.id===managedId));
  assert.equal((await call('PATCH',`/api/accounts/${managedId}`,tsa,{active:true})).statusCode,404);
  await assert.rejects(fixture.query('UPDATE users SET active=true WHERE id=$1',[managedId]),(e:any)=>e.code==='23514');
  // This buyer already has completed orders: deletion must preserve those foreign keys.
  await call('PATCH',`/api/accounts/${buyerA.id}`,tsa,{active:false});
  assert.equal((await call('DELETE',`/api/accounts/${buyerA.id}`,tsa)).statusCode,200);
  assert.ok((await one('SELECT count(*)::int AS n FROM orders WHERE created_by=$1',[buyerA.id])).n>0);
  check('superadmin resets without old password; inactive deletion hides accounts without breaking history or allowing reactivation');
  await fixture.query('UPDATE users SET active=false WHERE id=$1',[a.id]);
  assert.equal((await call('GET',customImage,ta)).statusCode,401);
  assert.equal((await call('GET',customImage,tbuyerA)).statusCode,401);
  assert.equal((await call('GET','/api/catalog',ta)).statusCode,401);check('disabled accounts lose API access immediately');
  for(let i=0;i<21;i++)await app.inject({method:'POST',url:'/api/auth/login',payload:{email:'none@test.local',password:'WrongPassword123'},remoteAddress:'192.0.2.33'});
  assert.equal((await app.inject({method:'POST',url:'/api/auth/login',payload:{email:'none@test.local',password:'WrongPassword123'},remoteAddress:'192.0.2.33'})).statusCode,429);check('login brute-force throttling');
  // Exercise destructive cleanup ONLY in this uniquely created scratch database.
  // Use a separate non-owner role with the same grants as cleanup-setup.ts.
  const cleanupPassword=randomBytes(36).toString('base64url');
  await owner.query(`CREATE ROLE "${cleanupRole}" LOGIN PASSWORD '${cleanupPassword}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS`);
  cleanupRoleCreated=true;
  await fixture.query(`GRANT CONNECT ON DATABASE "${database}" TO "${cleanupRole}"`);
  await fixture.query(`GRANT USAGE ON SCHEMA public TO "${cleanupRole}"`);
  await fixture.query(`GRANT SELECT ON ALL TABLES IN SCHEMA public TO "${cleanupRole}"`);
  await fixture.query(`GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO "${cleanupRole}"`);
  await fixture.query(`GRANT DELETE ON special_requests,inventory_movements,order_status_history,order_item_allocations,order_items,orders,inventory_batches,admin_products,vendors,admin_kitchens,audit_logs,product_templates,users,organizations TO "${cleanupRole}"`);
  await fixture.query(`GRANT INSERT ON audit_logs TO "${cleanupRole}"`);
  const cleanupUrl=new URL(ownerUrl);cleanupUrl.username=cleanupRole;cleanupUrl.password=cleanupPassword;
  process.env.ALLOW_DATA_RESET='true';process.env.DATA_RESET_DATABASE_URL=cleanupUrl.toString();
  process.env.DATA_RESET_BACKUP_DIR=join(imageTestDirectory,'cleanup-backups');process.env.NODE_ENV='production';
  const cleanup=await call('POST','/api/management/reset',tsa,{confirmation:'Ya, Saya Yakin Untuk Hapus Semua Data.',password});
  assert.equal(cleanup.statusCode,200,cleanup.body);
  assert.equal((await one('SELECT count(*)::int AS n FROM orders')).n,0);
  assert.equal((await one("SELECT count(*)::int AS n FROM users WHERE role<>'SUPERADMIN'")).n,0);
  assert.ok((await one("SELECT count(*)::int AS n FROM users WHERE role='SUPERADMIN' AND active")).n>0);
  assert.equal((await one("SELECT count(*)::int AS n FROM audit_logs WHERE action='RESET'")).n,1);
  assert.ok((await stat(join(process.env.DATA_RESET_BACKUP_DIR,cleanup.json().backupId))).size>0);
  check('production cleanup with a restricted non-owner connection creates a real pg_dump/media backup and preserves superadmins');
  console.log(`${checks} real-PostgreSQL security checks passed.`);
}finally{
  await app?.close();await runtime?.end();await fixture?.end();
  if(created)await owner.query(`DROP DATABASE "${database}" WITH (FORCE)`);
  if(cleanupRoleCreated&&/^borneo_cleanup_test_[a-f0-9]{32}$/.test(cleanupRole))await owner.query(`DROP ROLE "${cleanupRole}"`);
  await owner.end();
  // Exactly the uniquely created test directory, never live product storage.
  if(join(tmpdir(),imageTestDirectory.split(/[\\/]/).at(-1)!)===imageTestDirectory&&imageTestDirectory.split(/[\\/]/).at(-1)!.startsWith('borneo-private-images-test-'))await rm(imageTestDirectory,{recursive:true});
}
