import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {readFileSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
import pg from 'pg';
import bcrypt from 'bcryptjs';
import {apiDirectory,maintenancePool,maintenanceUrl} from './maintenance.js';

// All fixtures and destructive tests are confined to a uniquely created scratch DB.
const database=`borneo_security_test_${randomUUID().replaceAll('-','')}`;
if(!/^borneo_security_test_[a-f0-9]{32}$/.test(database))throw new Error('Invalid scratch DB name');
const owner=maintenancePool();
const ownerUrl=new URL(maintenanceUrl());ownerUrl.pathname=`/${database}`;
let fixture:pg.Pool|undefined;
let app:Awaited<ReturnType<typeof import('../server.js').buildApp>>|undefined;
let runtime:pg.Pool|undefined;
let created=false;
let checks=0;
function check(name:string){checks++;console.log(`PASS ${name}`);}
try{
  await owner.query(`CREATE DATABASE "${database}"`);created=true;
  fixture=new pg.Pool({connectionString:ownerUrl.toString()});
  const migrations=join(apiDirectory,'src/database/migrations');
  for(const file of readdirSync(migrations).filter(file=>file.endsWith('.sql')).sort())await fixture.query(readFileSync(join(migrations,file),'utf8'));
  // Exercise APIs with the same restricted role used by the local running server.
  const runtimeUrl=new URL(readFileSync(join(apiDirectory,'.env.runtime'),'utf8').match(/^DATABASE_URL=(.*)$/m)![1].trim());
  runtimeUrl.pathname=`/${database}`;
  await fixture.query('REVOKE CREATE ON SCHEMA public FROM PUBLIC');
  await fixture.query('GRANT USAGE ON SCHEMA public TO borneo_runtime');
  await fixture.query('GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO borneo_runtime');
  await fixture.query('REVOKE UPDATE,DELETE ON audit_logs,order_status_history,inventory_movements FROM borneo_runtime');
  process.env.NODE_ENV='test';process.env.DATABASE_URL=runtimeUrl.toString();process.env.JWT_SECRET=randomBytes(48).toString('hex');
  process.env.ALLOW_DATA_RESET='false';delete process.env.DATA_RESET_DATABASE_URL;
  const server=await import('../server.js');const client=await import('./client.js');runtime=client.pool;
  await client.assertRuntimeDatabaseRole();check('runtime role cannot own database/schema or bypass security');
  app=await server.buildApp();await app.ready();
  const one=async(sql:string,params:unknown[]=[]) => (await fixture!.query(sql,params)).rows[0];
  const cooperative=await one("INSERT INTO organizations(type,name) VALUES('COOPERATIVE','Test Cooperative') RETURNING id");
  const kitchenA=await one("INSERT INTO organizations(type,name) VALUES('KITCHEN','Kitchen A') RETURNING id");
  const kitchenB=await one("INSERT INTO organizations(type,name) VALUES('KITCHEN','Kitchen B') RETURNING id");
  const password=randomBytes(18).toString('base64url'),hash=await bcrypt.hash(password,4);
  const makeUser=(role:string,email:string,org:string)=>one('INSERT INTO users(organization_id,full_name,email,password_hash,role) VALUES($1,$2,$2,$3,$4) RETURNING id,email',[org,email,hash,role]);
  const sa=await makeUser('SUPERADMIN','sa@test.local',cooperative.id);
  const a=await makeUser('ADMIN','a@test.local',cooperative.id),b=await makeUser('ADMIN','b@test.local',cooperative.id);
  const buyerA=await makeUser('BUYER','buyer-a@test.local',kitchenA.id),buyerB=await makeUser('BUYER','buyer-b@test.local',kitchenB.id);
  await fixture.query('INSERT INTO admin_kitchens(admin_user_id,kitchen_id) VALUES($1,$2),($3,$4)',[a.id,kitchenA.id,b.id,kitchenB.id]);
  const login=async(email:string)=>{const r=await app!.inject({method:'POST',url:'/api/auth/login',payload:{email,password}});assert.equal(r.statusCode,200,r.body);return r.json().token as string;};
  const [ta,tb,tbuyerA,tbuyerB,tsa]=await Promise.all([a,b,buyerA,buyerB,sa].map(u=>login(u.email)));
  const call=(method:'GET'|'POST'|'PATCH'|'PUT',url:string,token:string,payload?:object)=>app!.inject({method,url,headers:{authorization:`Bearer ${token}`},payload});
  assert.equal((await app.inject({method:'GET',url:'/api/orders'})).statusCode,401);
  assert.equal((await call('GET','/api/users',tbuyerA)).statusCode,403);
  assert.equal((await call('GET','/api/reports/sales.pdf',tbuyerA)).statusCode,403);check('anonymous and buyer privilege escalation blocked');
  const template=await one("INSERT INTO product_templates(sku,name,category,order_unit,price_unit,owner_admin_user_id) VALUES('T-A','Private rice','Staples','kg','kg',$1) RETURNING id",[a.id]);
  const product=await one('INSERT INTO admin_products(admin_user_id,template_id,sale_price) VALUES($1,$2,10000) RETURNING id',[a.id,template.id]);
  assert.equal((await call('POST','/api/admin-products',tb,{templateId:template.id,salePrice:1})).statusCode,404);
  await assert.rejects(fixture.query('INSERT INTO admin_products(admin_user_id,template_id,sale_price) VALUES($1,$2,1)',[b.id,template.id]),(e:any)=>e.code==='23514');check('private product cross-tenant access blocked by API and DB');
  assert.equal((await call('POST','/api/stock',ta,{adminProductId:product.id,quantity:100,salePrice:10000,source:'COOPERATIVE'})).statusCode,200);
  assert.equal((await call('POST','/api/stock',tb,{adminProductId:product.id,quantity:10,salePrice:1})).statusCode,404);
  assert.equal((await call('POST','/api/stock',ta,{customProduct:{name:'Bad',category:'Bad',unit:'kg',image:'javascript:alert(1)'},quantity:1,salePrice:10})).statusCode,400);check('stock ownership and image input validation');
  const payload={neededDate:'2026-10-01',idempotencyKey:randomUUID(),items:[{adminProductId:product.id,quantity:10}]};
  assert.equal((await call('POST','/api/orders',tbuyerB,payload)).statusCode,409);
  const duplicates=await Promise.all([call('POST','/api/orders',tbuyerA,payload),call('POST','/api/orders',tbuyerA,payload)]);
  duplicates.forEach(r=>assert.equal(r.statusCode,200,r.body));assert.equal(duplicates[0].json().id,duplicates[1].json().id);
  const id=duplicates[0].json().id;
  assert.equal((await one('SELECT count(*)::int AS n FROM orders')).n,1);
  assert.equal(Number((await one('SELECT quantity_reserved FROM inventory_batches')).quantity_reserved),10);check('concurrent checkout retry reserves once');
  assert.equal((await call('GET','/api/orders',tbuyerB)).json().length,0);
  assert.equal((await call('GET','/api/orders',tb)).json().length,0);
  assert.equal((await call('PATCH',`/api/orders/${id}/status`,tb,{status:'CANCELLED'})).statusCode,404);check('orders isolated across admins and kitchens');
  const allocation=await one('SELECT id FROM order_item_allocations');
  assert.equal((await call('PATCH',`/api/allocations/${allocation.id}/prepared`,ta,{prepared:true})).statusCode,200);
  const ships=await Promise.all([call('PATCH',`/api/orders/${id}/status`,ta,{status:'SHIPPED'}),call('PATCH',`/api/orders/${id}/status`,ta,{status:'SHIPPED'})]);
  assert.deepEqual(ships.map(r=>r.statusCode).sort(),[200,409]);
  assert.equal(Number((await one('SELECT quantity_available FROM inventory_batches')).quantity_available),90);
  assert.equal(Number((await one('SELECT quantity_reserved FROM inventory_batches')).quantity_reserved),0);
  assert.equal((await one("SELECT count(*)::int AS n FROM inventory_movements WHERE movement_type='OUT'")).n,1);check('concurrent shipment cannot subtract stock twice');
  assert.equal((await call('PATCH',`/api/allocations/${allocation.id}/prepared`,ta,{prepared:false})).statusCode,409);
  assert.equal((await call('PATCH',`/api/orders/${id}/status`,ta,{status:'AWAITING_KITCHEN'})).statusCode,200);
  assert.equal((await call('PATCH',`/api/orders/${id}/status`,ta,{status:'COMPLETED'})).statusCode,403);
  assert.equal((await call('PATCH',`/api/orders/${id}/status`,tbuyerA,{status:'COMPLETED'})).statusCode,200);check('post-shipment edits blocked and kitchen confirms receipt');
  const second=await call('POST','/api/orders',tbuyerA,{...payload,idempotencyKey:randomUUID()});assert.equal(second.statusCode,200,second.body);
  const cancels=await Promise.all([call('PATCH',`/api/orders/${second.json().id}/status`,tbuyerA,{status:'CANCELLED'}),call('PATCH',`/api/orders/${second.json().id}/status`,tbuyerA,{status:'CANCELLED'})]);
  assert.deepEqual(cancels.map(r=>r.statusCode).sort(),[200,409]);
  assert.equal(Number((await one('SELECT quantity_available FROM inventory_batches')).quantity_available),90);check('concurrent cancellation releases stock only once');
  assert.equal((await call('GET','/api/reports/sales',tb)).json().length,0);
  assert.equal((await call('GET','/api/reports/sales',ta)).json().length,1);
  assert.equal((await call('GET','/api/reports/sales.pdf',ta)).statusCode,200);
  assert.equal((await call('GET','/api/reports/sales.xls',ta)).statusCode,200);check('reports isolated and PDF/Excel generation works');
  const weightedTemplate=await one("INSERT INTO product_templates(sku,name,category,order_unit,price_unit,weighing_required,estimated_kg_per_unit) VALUES('T-W','Chicken','Protein','potong','kg',true,0.8) RETURNING id");
  const weightedProduct=await one('INSERT INTO admin_products(admin_user_id,template_id,sale_price) VALUES($1,$2,30000) RETURNING id',[a.id,weightedTemplate.id]);
  assert.equal((await call('POST','/api/stock',ta,{adminProductId:weightedProduct.id,quantity:20,salePrice:30000,source:'COOPERATIVE'})).statusCode,200);
  const weighted=await call('POST','/api/orders',tbuyerA,{...payload,idempotencyKey:randomUUID(),items:[{adminProductId:weightedProduct.id,quantity:10}]});
  assert.equal(weighted.statusCode,200,weighted.body);
  const weightedId=weighted.json().id;
  const weightedItem=await one('SELECT id FROM order_items WHERE order_id=$1',[weightedId]);
  const weightedAllocation=await one('SELECT id FROM order_item_allocations WHERE order_item_id=$1',[weightedItem.id]);
  assert.equal((await call('PATCH',`/api/allocations/${weightedAllocation.id}/prepared`,ta,{prepared:true})).statusCode,200);
  assert.equal((await call('PATCH',`/api/orders/${weightedId}/status`,ta,{status:'SHIPPED'})).statusCode,409);
  assert.equal((await call('PATCH',`/api/order-items/${weightedItem.id}/actual-weight`,tb,{actualWeightKg:9})).statusCode,404);
  assert.equal((await call('PATCH',`/api/order-items/${weightedItem.id}/actual-weight`,ta,{actualWeightKg:21})).statusCode,200);
  assert.equal((await call('PATCH',`/api/orders/${weightedId}/status`,ta,{status:'SHIPPED'})).statusCode,409);
  assert.equal(Number((await one('SELECT quantity_reserved FROM inventory_batches WHERE admin_product_id=$1',[weightedProduct.id])).quantity_reserved),8);
  assert.equal((await call('PATCH',`/api/order-items/${weightedItem.id}/actual-weight`,ta,{actualWeightKg:9})).statusCode,200);
  assert.equal((await call('PATCH',`/api/orders/${weightedId}/status`,ta,{status:'SHIPPED'})).statusCode,200);
  assert.equal(Number((await one('SELECT quantity_available FROM inventory_batches WHERE admin_product_id=$1',[weightedProduct.id])).quantity_available),11);
  assert.equal(Number((await one('SELECT final_total FROM orders WHERE id=$1',[weightedId])).final_total),270000);
  check('actual weight is mandatory, tenant-scoped and stock shortage rolls back atomically');
  const special=await call('POST','/api/special-requests',tbuyerA,{name:'Special flour',quantity:3,unit:'karung'});
  assert.equal(special.statusCode,200,special.body);
  const approval={source:'VENDOR',vendorName:'Test Supplier',unit:'karung',salePrice:200000};
  assert.equal((await call('PATCH',`/api/special-requests/${special.json().id}/approve`,tb,approval)).statusCode,404);
  const approvals=await Promise.all([call('PATCH',`/api/special-requests/${special.json().id}/approve`,ta,approval),call('PATCH',`/api/special-requests/${special.json().id}/approve`,ta,approval)]);
  assert.deepEqual(approvals.map(r=>r.statusCode).sort(),[200,404]);
  const specialOrderId=approvals.find(r=>r.statusCode===200)!.json().orderId;
  const specialAllocation=await one('SELECT a.id FROM order_item_allocations a JOIN order_items i ON i.id=a.order_item_id WHERE i.order_id=$1',[specialOrderId]);
  assert.equal((await call('PATCH',`/api/allocations/${specialAllocation.id}/prepared`,ta,{prepared:true})).statusCode,200);
  assert.equal((await call('PATCH',`/api/orders/${specialOrderId}/status`,ta,{status:'SHIPPED'})).statusCode,200);
  check('special request approval is tenant-scoped, idempotent and vendor order ships');
  const partner=await call('POST','/api/partners',ta,{name:'New Kitchen',phone:'081234567890',address:'Test street 123',gmapsUrl:'https://maps.google.com/'});
  assert.equal(partner.statusCode,200,partner.body);assert.notEqual(partner.json().temporaryPassword,'Demo123!');assert.ok(partner.json().temporaryPassword.length>=24);check('new partners get unique strong passwords');
  await assert.rejects(runtime.query('DELETE FROM audit_logs'),(e:any)=>e.code==='42501');
  await assert.rejects(runtime.query('CREATE TABLE public.forbidden(id int)'),(e:any)=>e.code==='42501');
  await assert.rejects(fixture.query('UPDATE inventory_batches SET quantity_available=1000'),(e:any)=>e.code==='23514');check('DB blocks audit erasure, DDL and impossible stock');
  assert.equal((await call('POST','/api/management/reset',tsa,{confirmation:'Ya, Saya Yakin Untuk Hapus Semua Data.',password})).statusCode,403);check('reset disabled without explicit maintenance configuration');
  await fixture.query('UPDATE users SET active=false WHERE id=$1',[a.id]);
  assert.equal((await call('GET','/api/catalog',ta)).statusCode,401);check('disabled accounts lose API access immediately');
  for(let i=0;i<21;i++)await app.inject({method:'POST',url:'/api/auth/login',payload:{email:'none@test.local',password:'WrongPassword123'},remoteAddress:'192.0.2.33'});
  assert.equal((await app.inject({method:'POST',url:'/api/auth/login',payload:{email:'none@test.local',password:'WrongPassword123'},remoteAddress:'192.0.2.33'})).statusCode,429);check('login brute-force throttling');
  console.log(`${checks} real-PostgreSQL security checks passed.`);
}finally{
  await app?.close();await runtime?.end();await fixture?.end();
  if(created)await owner.query(`DROP DATABASE "${database}" WITH (FORCE)`);
  await owner.end();
}
